
import { Unit, Word, Tense } from './types';

export const CUSTOM_VOCAB: Record<string, Word[]> = {
  SHORT: [
    { id: 's-1', en: 'the', uz: 'aniq artikl' },
    { id: 's-2', en: 'a / an', uz: 'noaniq artikl, bir, bitta' },
    { id: 's-3', en: 'to', uz: "yo'nalish kelishigi (ga), maqsad (uchun)" },
    { id: 's-4', en: 'of', uz: 'qaratqich kelishigi (ning)' },
    { id: 's-5', en: 'in', uz: "o'rin-payt kelishigi (da), ichida" },
    { id: 's-6', en: 'on', uz: 'ustida, sirtida' },
    { id: 's-7', en: 'at', uz: 'aniq bir joyda (da)' },
    { id: 's-8', en: 'for', uz: 'uchun' },
    { id: 's-9', en: 'with', uz: 'bilan' },
    { id: 's-10', en: 'from', uz: 'dan' },
    { id: 's-11', en: 'is', uz: "dir, bo'lmoq (hozirgi zamon)" },
    { id: 's-12', en: 'are', uz: "dir, bo'lmoq (hozirgi zamon)" },
    { id: 's-13', en: 'was', uz: "edi, bo'lgan (o'tgan zamon)" },
    { id: 's-14', en: 'were', uz: "edi, bo'lgan (o'tgan zamon)" },
    { id: 's-15', en: 'be', uz: "bo'lmoq, mavjud bo'lmoq" },
    { id: 's-16', en: 'have', uz: "ega bo'lmoq, bor bo'lmoq" },
    { id: 's-17', en: 'has', uz: "ega bo'lmoq, bor bo'lmoq (u)" },
    { id: 's-18', en: 'do', uz: 'qilmoq, bajarmoq' },
    { id: 's-19', en: 'go', uz: 'bormoq' },
    { id: 's-20', en: 'get', uz: 'olmoq' },
    { id: 's-21', en: 'see', uz: "ko'rmoq" },
    { id: 's-22', en: 'say', uz: 'aytmoq' },
    { id: 's-23', en: 'make', uz: 'yasamoq, yaratmoq, qilmoq' },
    { id: 's-24', en: 'I', uz: 'men' },
    { id: 's-25', en: 'you', uz: 'sen / siz' },
    { id: 's-26', en: 'he', uz: 'u (erkak jinsiga nisbatan)' },
    { id: 's-27', en: 'she', uz: 'u (ayol jinsiga nisbatan)' },
    { id: 's-28', en: 'it', uz: 'u (narsa va hayvonlarga nisbatan)' },
    { id: 's-29', en: 'we', uz: 'biz' },
    { id: 's-30', en: 'they', uz: 'ular' },
    { id: 's-31', en: 'me', uz: 'meni / menga' },
    { id: 's-32', en: 'him', uz: 'uni, unga (erkak jinsiga nisbatan)' },
    { id: 's-33', en: 'her', uz: 'uni, unga (ayol jinsiga nisbatan)' },
    { id: 's-34', en: 'my', uz: 'mening' },
    { id: 's-35', en: 'your', uz: 'sening / sizning' },
    { id: 's-36', en: 'his', uz: 'uning (erkak jinsiga nisbatan)' },
    { id: 's-37', en: 'and', uz: 'va' },
    { id: 's-38', en: 'or', uz: 'yoki' },
    { id: 's-39', en: 'but', uz: 'lekin' },
    { id: 's-40', en: 'if', uz: 'agar, basharti' },
    { id: 's-41', en: 'so', uz: 'shuning uchun, shunday qilib' },
    { id: 's-42', en: 'not', uz: 'emas' },
    { id: 's-43', en: 'no', uz: "yo'q" },
    { id: 's-44', en: 'yes', uz: 'ha' },
    { id: 's-45', en: 'this', uz: 'bu' },
    { id: 's-46', en: 'that', uz: "u, ana u, o'sha" },
    { id: 's-47', en: 'here', uz: 'bu yerda' },
    { id: 's-48', en: 'there', uz: 'u yerda' },
    { id: 's-49', en: 'what', uz: 'nima' },
    { id: 's-50', en: 'who', uz: 'kim' },
    { id: 's-51', en: 'when', uz: 'qachon' },
    { id: 's-52', en: 'where', uz: 'qayerda' },
    { id: 's-53', en: 'can', uz: 'qila olmoq, imkoniyati bo\'lmoq' },
    { id: 's-54', en: 'will', uz: 'qilaman (kelasi zamon)' }
  ],
  B_PLUS: [
    // TOPIC VOCABULARY (UNIT 3)
    { id: 'b-1', en: 'beat', uz: "yengmoq, mag'lub etmoq" },
    { id: 'b-2', en: 'board game', uz: "stoli o'yini, doska o'yini" },
    { id: 'b-3', en: 'captain', uz: 'sardor (kapitan)' },
    { id: 'b-4', en: 'challenge', uz: 'chaqiruv (musobaqaga)' },
    { id: 'b-5', en: 'champion', uz: 'champion' },
    { id: 'b-6', en: 'cheat', uz: "g'irromlik qilmoq, aldash" },
    { id: 'b-7', en: 'classical music', uz: 'mumtoz musiqa' },
    { id: 'b-8', en: 'club', uz: 'klub' },
    { id: 'b-9', en: 'coach', uz: 'murabbiy' },
    { id: 'b-10', en: 'competition', uz: 'musobaqa' },
    { id: 'b-11', en: 'concert', uz: 'konsert' },
    { id: 'b-12', en: 'defeat', uz: "mag'lubiyat, mag'lub etmoq" },
    { id: 'b-13', en: 'entertaining', uz: 'ko\'ngilochar' },
    { id: 'b-14', en: 'folk music', uz: 'folklor musiqa' },
    { id: 'b-15', en: 'group', uz: 'guruh' },
    { id: 'b-16', en: 'gym', uz: 'sport zali, gimnastika zali' },
    { id: 'b-17', en: 'have fun', uz: 'xursandchilik qilmoq' },
    { id: 'b-18', en: 'interest', uz: 'qiziqtirmoq' },
    { id: 'b-19', en: 'member', uz: "a'zo" },
    { id: 'b-20', en: 'opponent', uz: 'raqib, qarshi tomon' },
    { id: 'b-21', en: 'organize', uz: 'tashkillashtirmoq, uyushtirmoq' },
    { id: 'b-22', en: 'pleasure', uz: 'rohat' },
    { id: 'b-23', en: 'referee', uz: 'hakam' },
    { id: 'b-24', en: 'rhythm', uz: 'marom / maqom' },
    { id: 'b-25', en: 'risk', uz: 'tavakkal qilmoq, xavf-xatarga qo\'yish' },
    { id: 'b-26', en: 'score', uz: 'ochko (gol kiritmoq)' },
    { id: 'b-27', en: 'support', uz: "qo'llab-quvvatlash" },
    { id: 'b-28', en: 'team', uz: 'jamoa' },
    { id: 'b-29', en: 'train', uz: "shug'ullanmoq, mashq qilmoq" },
    { id: 'b-30', en: 'video game', uz: "kompyuter o'yini" },
    
    // PHRASAL VERBS
    { id: 'b-31', en: 'Carry on', uz: 'davom ettirmoq' },
    { id: 'b-32', en: 'Eat out', uz: 'restoranda ovqatlanmoq' },
    { id: 'b-33', en: 'Give up', uz: 'taslim bo\'lmoq, odatni tashlamoq' },
    { id: 'b-34', en: 'Join in', uz: "qo'shilmoq, ishtirok etmoq" },
    { id: 'b-35', en: 'Send off', uz: "o'yindan chetlashtirmoq" },
    { id: 'b-36', en: 'Take up', uz: 'shug\'ullanishni boshlamoq (hobby, sport)' },
    { id: 'b-37', en: 'Turn down', uz: 'rad etmoq, ovozni pasaytirmoq' },
    { id: 'b-38', en: 'Turn up', uz: 'paydo bo\'lmoq, ovozni ko\'tarmoq' },

    // PREPOSITIONAL PHRASES
    { id: 'b-39', en: 'For a long time', uz: 'uzoq vaqt mobaynida' },
    { id: 'b-40', en: 'For fun', uz: 'ermak uchun' },
    { id: 'b-41', en: 'In the middle (of)', uz: "ning o'rtasida" },
    { id: 'b-42', en: 'In time (for)', uz: 'o\'z vaqtida, kechikmasdan' },
    { id: 'b-43', en: 'On CD/DVD/video', uz: 'CD/DVD/videoda' },
    { id: 'b-44', en: 'On stage', uz: 'sahnada' },

    // WORD FORMATION (SELECTED)
    { id: 'b-45', en: 'Athlete', uz: 'atletikachi, sportchi' },
    { id: 'b-46', en: 'Childhood', uz: 'bolalik' },
    { id: 'b-47', en: 'Collection', uz: 'kolleksiya' },
    { id: 'b-48', en: 'Entertainer', uz: "so'z ustasi, qiziqchi, ko'ngilochar shaxs" },
    { id: 'b-49', en: 'Heroic', uz: 'mardlarcha' },
    { id: 'b-50', en: 'Musical', uz: 'musiqiy' },
    { id: 'b-51', en: 'Player', uz: "o'yinchi" },
    { id: 'b-52', en: 'Sailing', uz: 'dengiz safari' },
    { id: 'b-53', en: 'Singing', uz: 'kuylash' },

    // WORD PATTERNS
    { id: 'b-54', en: 'Bored with', uz: 'dan zerikmoq' },
    { id: 'b-55', en: 'Crazy about', uz: "ga juda ham qiziqmoq, jinnisi bo'lmoq" },
    { id: 'b-56', en: 'Good at', uz: 'dan yaxshi' },
    { id: 'b-57', en: 'Interested in', uz: 'ga qiziqmoq' },
    { id: 'b-58', en: 'Keen on', uz: "ga ishqiboz bo'lmoq" },
    { id: 'b-59', en: 'Popular with', uz: 'orasida mashhur, ommabop' },
    { id: 'b-60', en: 'Feel like', uz: 'xohlamoq, istamoq' },
    { id: 'b-61', en: 'Take part in', uz: 'da ishtirok etmoq, qatnashmoq' },

    // UNIT 6 TOPIC VOCABULARY
    { id: 'b-62', en: 'Achieve', uz: 'erishmoq' },
    { id: 'b-63', en: 'Brain', uz: 'miya / aql' },
    { id: 'b-64', en: 'Clever', uz: 'aqlli' },
    { id: 'b-65', en: 'Concentrate', uz: 'diqqatni jamlamoq' }
  ],
  C_PLUS: []
};

export const VOCAB_DATA: Unit[] = [
  {
    id: 'unit-1',
    title: 'Unit 1: Education',
    icon: '🎓',
    words: [
      { id: '1-1', en: 'To educate', uz: "ta’lim bermoq" },
      { id: '1-2', en: 'Compulsory education', uz: "majburiy ta’lim" },
      { id: '1-3', en: 'Preschool education', uz: "maktabgacha ta’lim" },
      { id: '1-4', en: 'Higher education ( tertiary education )', uz: "oliy ta’lim" },
      { id: '1-5', en: 'Qualification', uz: "malaka" },
      { id: '1-6', en: 'Bachelor’s degree', uz: "bakalavr darajasi" },
      { id: '1-7', en: 'Master’s degree', uz: "magistratura" },
      { id: '1-8', en: 'Doctorate ( PhD)', uz: "doktorantura" },
      { id: '1-9', en: 'Headteacher/ principal', uz: "maktab direktori" },
      { id: '1-10', en: 'Tutor', uz: "repetitor" },
      { id: '1-11', en: 'mature student', uz: "yoshi katta talaba" },
      { id: '1-12', en: 'a graduate', uz: "bitiruvchi" },
      { id: '1-13', en: 'curriculum', uz: "dars jadvali" },
      { id: '1-14', en: 'Humanities', uz: "gumanitar fanlar" },
      { id: '1-15', en: 'to play truant', uz: "besabab dars qoldirmoq" },
      { id: '1-16', en: 'to skip classes', uz: "darslardan qochmoq" },
      { id: '1-17', en: 'Bookworm', uz: "kitob o’qishni yoqtiruvchi inson" },
      { id: '1-18', en: 'rote learning', uz: "ko’r-ko’rona yodlamoq" },
      { id: '1-19', en: 'Literacy rate', uz: "savodxonlik darajasi" },
      { id: '1-20', en: 'Literate ( illiterate)', uz: "savodli ( savodsiz)" },
      { id: '1-21', en: 'extra-curricular activities', uz: "qo’shimcha mashg’ulotlar" },
      { id: '1-22', en: 'Discipline', uz: "intizom" },
      { id: '1-23', en: 'halls of residence / dormitory', uz: "talabalar turar joyi" },
      { id: '1-24', en: 'Assignment', uz: "vazifa, topshiriq" },
      { id: '1-25', en: 'distance learning', uz: "masofaviy ta’lim" },
      { id: '1-26', en: 'to sit (take) an exam', uz: "imtihon topshirmoq" },
      { id: '1-27', en: 'tuition fee', uz: "kontrakt to’lovi" },
      { id: '1-28', en: 'a student loan', uz: "talim krediti" },
      { id: '1-29', en: 'Internship', uz: "amaliyot" },
      { id: '1-30', en: 'to work your way through university', uz: "ham o’qib ham ishlamoq" },
      { id: '1-31', en: 'to fall behind with your studies', uz: "o’qishda orqada qolmoq" },
      { id: '1-32', en: 'to learn something by heart / memorize', uz: "yodlamoq" },
      { id: '1-33', en: 'gap year', uz: "akademik ta’til" },
      { id: '1-34', en: 'to drop out', uz: "o’qishni tashlamoq" },
      { id: '1-35', en: 'well-educated', uz: "yaxshi ta’lim olgan" },
      { id: '1-36', en: 'to revise/review', uz: "takrorlamoq, mustahkamlamoq" },
      { id: '1-37', en: 'to pass with flying colours', uz: "imtihondan alo baholar bilan o’tmoq" },
      { id: '1-38', en: 'to resit/retake an exam', uz: "imtihonni qayta topshirmoq" }
    ]
  },
  {
    id: 'unit-2',
    title: 'Unit 2: Hometown & Neighbourhood',
    icon: '🏡',
    words: [
      { id: '2-1', en: 'To be born and raised/bred in', uz: "tug’ilib katta bo’lmoq" },
      { id: '2-2', en: 'To be located/situated in', uz: "da joylashmoq" },
      { id: '2-3', en: 'in the southern/northern part of the country', uz: "davlatning janubiy/shimoliy qismida" },
      { id: '2-4', en: 'coastal city', uz: "qirg’oq shahar" },
      { id: '2-5', en: 'commercial center', uz: "tijoriy markaz" },
      { id: '2-6', en: 'suburbs/outskirts', uz: "shahar tashqarisi" },
      { id: '2-7', en: 'residential area', uz: "turar joy" },
      { id: '2-8', en: 'city center/inner city', uz: "shahar markazi" },
      { id: '2-9', en: 't0 be famous for/renown for', uz: "bilan mashhur" },
      { id: '2-10', en: 'good atmosphere', uz: "yaxshi atmosfera" },
      { id: '2-11', en: 'colourful/vibrant city', uz: "rangdor/ zavqli shahar" },
      { id: '2-12', en: 'well-developed', uz: "yaxshi rivojlangan" },
      { id: '2-13', en: 'good infrastructure', uz: "yaxshi infrastruktura" },
      { id: '2-14', en: 'good facilities', uz: "yaxshi qulayliklar" },
      { id: '2-15', en: 'lively markets/bars/restaurants', uz: "jo’shqin bozorlar/barlar/restorantlar" },
      { id: '2-16', en: 'great nightlife', uz: "ajoyib tungi hayot" },
      { id: '2-17', en: 'friendly neighbours', uz: "do’stona qo’shnilar" },
      { id: '2-18', en: 'traffic congestion', uz: "mashinalar tirbandligi" },
      { id: '2-19', en: 'air pollution', uz: "havo ifloslanishi" },
      { id: '2-20', en: 'to be densely populated/overcrowded', uz: "aholi zich joylashgan" },
      { id: '2-21', en: 'Touristic', uz: "turistik" },
      { id: '2-22', en: 'Bustling', uz: "gavjum, jo’shqin ( bustling place/city)" },
      { id: '2-23', en: 'Hectic', uz: "juda band ( hectic lifestyle )" },
      { id: '2-24', en: 'Contemporary', uz: "zamonaviy" },
      { id: '2-25', en: 'Sprawling', uz: "keng hududga cho’zilgan ( sprawling city )" },
      { id: '2-26', en: 'Orchard', uz: "mevazor" },
      { id: '2-27', en: 'Picturesque', uz: "chiroyli ( picturesque place )" },
      { id: '2-28', en: 'High-rise', uz: "ko’p qavatli" },
      { id: '2-29', en: 'Close-knit', uz: "ahil" },
      { id: '2-30', en: 'Upmarket', uz: "yuqori tabaqa insonlar uchun mo’ljallangan" },
      { id: '2-31', en: 'Out-of-town', uz: "shahar tashqarisidagi" },
      { id: '2-32', en: 'Pop-up shop', uz: "yarmarka , vaqtinchalik do’konlar" },
      { id: '2-33', en: 'Rural', uz: "qishloqqa oid ( rural area – qishloq joy)" }
    ]
  },
  {
    id: 'unit-3',
    title: 'Unit 3: Accommodation',
    icon: '🏢',
    words: [
      { id: '3-1', en: 'Property', uz: "mulk" },
      { id: '3-2', en: 'Single-storey', uz: "bir qavatli" },
      { id: '3-3', en: 'Two-storey', uz: "ikki qavatli" },
      { id: '3-4', en: 'Flat/apartment', uz: "ko’p qavatli xonadon" },
      { id: '3-5', en: 'fully-furnished flat / apartment', uz: "to’liq jihozlangan kvartira" },
      { id: '3-6', en: 'block of flats / tower block', uz: "ko’p qavatli kvartira" },
      { id: '3-7', en: 'penthouse', uz: "bino tepasidagi qimmat uy" },
      { id: '3-8', en: 'mansion', uz: "hashamatli uy, koshona" },
      { id: '3-9', en: 'downtown', uz: "shahar markazi" },
      { id: '3-10', en: 'housing estate', uz: "bir nechta bir xildagi uylar kvartali" },
      { id: '3-11', en: 'to be within walking distance', uz: "yaqinda joylashgan" },
      { id: '3-12', en: 'dining room', uz: "ovqatlanadigan xona" },
      { id: '3-13', en: 'hall / hallway', uz: "koridor" },
      { id: '3-14', en: 'basement / cellar', uz: "yerto’la" },
      { id: '3-15', en: 'attic / loft', uz: "boloxona" },
      { id: '3-16', en: 'balcony', uz: "balkon" },
      { id: '3-17', en: 'to rent out / let out', uz: "uyini ijaraga bermoq" },
      { id: '3-18', en: 'landlord / landlady', uz: "ijara beruvchi" },
      { id: '3-19', en: 'tenant', uz: "ijarada turuvchi odam" },
      { id: '3-20', en: 'evict', uz: "uydan haydab chiqarmoq" },
      { id: '3-21', en: 'estate agent (UK) / real estate agent (US)', uz: "makler" },
      { id: '3-22', en: 'mortgage', uz: "ipoteka krediti" },
      { id: '3-23', en: '(all the) mod cons', uz: "barcha uy jihozlari ( gaz,muzlatkich,pech va hokazolar )" },
      { id: '3-24', en: 'fitted kitchen', uz: "to’liq jihozlangan oshxona" },
      { id: '3-25', en: 'utilities', uz: "kommunal taminotlar/xizmatlar ( gaz,elektr,svet )" },
      { id: '3-26', en: 'spacious', uz: "keng" },
      { id: '3-27', en: 'cosy', uz: "shinam" },
      { id: '3-28', en: 'elevator (US) / lift (UK)', uz: "lift" },
      { id: '3-29', en: 'lawn', uz: "gazon" },
      { id: '3-30', en: 'terrace / patio', uz: "ayvon, peshayvon" },
      { id: '3-31', en: 'fence', uz: "to’siq" },
      { id: '3-32', en: 'to redecorate', uz: "qayta dekoratsiyalamoq" },
      { id: '3-33', en: 'to renovate', uz: "remont qilmoq" },
      { id: '3-34', en: 'to do up a property', uz: "eski uyni tamirlamoq" },
      { id: '3-35', en: 'to paper the walls', uz: "devorga gulqog’oz yopishtirmoq ( oboylamoq )" },
      { id: '3-36', en: 'dream home', uz: "orzudagi uy" },
      { id: '3-37', en: 'house-warming party', uz: "uy bazmi ( yangi uy qurilganda )" },
      { id: '3-38', en: 'to move in/out', uz: "ko’chib kirmoq/chiqmoq" },
      { id: '3-39', en: 'downsize', uz: "kichikroq uyga ko’chmoq" },
      { id: '3-40', en: 'to feel homesick', uz: "uyni sog’inmoq" },
      { id: '3-41', en: 'there’s no place like home', uz: "o’z uying o’lan to’shaging" }
    ]
  },
  {
    id: 'unit-4',
    title: 'Unit 4: Hobbies & Interests',
    icon: '🎯',
    words: [
      { id: '4-1', en: 'Spare time', uz: "bo’sh vaqt" },
      { id: '4-2', en: 'Unwind', uz: "zavqlanmoq, rohat olmoq" },
      { id: '4-3', en: 'To blow off steam', uz: "xordiq chiqarmoq" },
      { id: '4-4', en: 'Can’t get enough of …', uz: "… dan to’ymaslik ( biror mashg’ulotni judayam yoqtirmoq" },
      { id: '4-5', en: 'To take up a hobby', uz: "yangi hobbini boshlamoq" },
      { id: '4-6', en: 'To be passionate about/ keen on', uz: "ga judayam qiziqmoq" },
      { id: '4-7', en: 'Pastime', uz: "bo’sh vaqt" },
      { id: '4-8', en: 'Work out', uz: "shug’ullanmoq, mashq qilmoq" },
      { id: '4-9', en: 'To relieve stress', uz: "stresni chiqarmoq" },
      { id: '4-10', en: 'Get into nature', uz: "tabiat qo’yniga chiqmoq" },
      { id: '4-11', en: 'Hang out', uz: "sayr qilmoq ( shunchaki maqsadsiz)" },
      { id: '4-12', en: 'Catch up with friends', uz: "do’stlar bilan uchrashmoq" },
      { id: '4-13', en: 'Uplifting', uz: "kayfiyatni ko’taruvchi" },
      { id: '4-14', en: 'Adrenaline pumping', uz: "adrenalin beruvchi" },
      { id: '4-15', en: 'Energizing', uz: "shijoatli, quvvatli" },
      { id: '4-16', en: 'Music/arts/computer buff', uz: "musiqa/sanat/kompyuter bilimdoni" },
      { id: '4-17', en: 'Surf the net', uz: "internetda o’tirmoq" },
      { id: '4-18', en: 'Cinemagoer/movie buff', uz: "kino ixlosmandi" },
      { id: '4-19', en: 'Fight boredom', uz: "zerikishga qarshi kurashmoq" },
      { id: '4-20', en: 'Distract', uz: "chalg’itmoq" },
      { id: '4-21', en: 'Calming/therapeutic', uz: "tinchlantiruvchi" },
      { id: '4-22', en: '(on my )Bucket list', uz: "o’lguncha bajarishni xohlagan ishlar ro’yxati" },
      { id: '4-23', en: 'Socialize', uz: "odamlarga qo’shilmoq, odamlar bilan gaplashmoq" },
      { id: '4-24', en: 'Back then', uz: "avvallari, o’tmishda" },
      { id: '4-25', en: 'Out-of-the-box thinking', uz: "noodatiy fikrlash" },
      { id: '4-26', en: 'Set aside some time', uz: "biroz vaqt ajratmoq" },
      { id: '4-27', en: 'To have a stroll', uz: "sayr qilmoq, aylanmoq" },
      { id: '4-28', en: 'Meet up with friends', uz: "do’stlar bilan uchrashmoq" },
      { id: '4-29', en: 'Let my hair down', uz: "dam olmoq, hordiq chiqarmoq" },
      { id: '4-30', en: 'Jogging', uz: "yugurish" },
      { id: '4-31', en: 'Beekeeping', uz: "asalarichilik" }
    ]
  },
  {
    id: 'unit-5',
    title: 'Unit 5: Personality',
    icon: '👤',
    words: [
      { id: '5-1', en: 'Broad-minded', uz: "keng fikrli" },
      { id: '5-2', en: 'Easy-going', uz: "yuragi keng ( tez asabiylashmaydigan)" },
      { id: '5-3', en: 'Extrovert', uz: "chqiqshuvchan, kirishuvchan" },
      { id: '5-4', en: 'Fair-minded', uz: "adolatli, xolis ( hammaga teng munosabat qiladi)" },
      { id: '5-5', en: 'Fun-loving', uz: "xushchaqchaq" },
      { id: '5-6', en: 'Good company', uz: "yaxshi xamroh" },
      { id: '5-7', en: 'Have a sense of humour', uz: "hazilkash" },
      { id: '5-8', en: 'Introvert', uz: "odamovi, kamgap" },
      { id: '5-9', en: 'Laid-back', uz: "yuragi keng" },
      { id: '5-10', en: 'To lose one’s temper', uz: "tez jahli chiqmoq" },
      { id: '5-11', en: 'Narrow-minded', uz: "tor fikrlovchi" },
      { id: '5-12', en: 'Painfully shy', uz: "judayam uyatchang" },
      { id: '5-13', en: 'To put others first', uz: "boshqalarni o’ylamoq" },
      { id: '5-14', en: 'Quick-tempered', uz: "qiziqqon" },
      { id: '5-15', en: 'Reserved', uz: "uyatchang" },
      { id: '5-16', en: 'Self-assured', uz: "o’ziga ishonchi baland" },
      { id: '5-17', en: 'Self-centred', uz: "xudbin" },
      { id: '5-18', en: 'Self-confident', uz: "o’ziga ishonadigan" },
      { id: '5-19', en: 'Self-effacing', uz: "oddiy, sipo ( etibor tortmay chetda yuradi)" },
      { id: '5-20', en: 'To take after / resemble', uz: "o’xshamoq" },
      { id: '5-21', en: 'Thick-skinned', uz: "terisi qalin" },
      { id: '5-22', en: 'Trustworthy', uz: "ishonchli, ishonsa bo’ladigan" },
      { id: '5-23', en: 'Two-faced/hypocritical', uz: "ikkiyuzlamachi, munofiq" },
      { id: '5-24', en: 'Supportive', uz: "g’amxo’r, dalda beradigan" },
      { id: '5-25', en: 'Cheerful', uz: "quvnoq" },
      { id: '5-26', en: 'Stingy, mean', uz: "xasis" },
      { id: '5-27', en: 'Overweight/chubby', uz: "semiz, lo’ppia" },
      { id: '5-28', en: 'Brunette', uz: "qorasoch" },
      { id: '5-29', en: 'Curly', uz: "jingalak" },
      { id: '5-30', en: 'Moody', uz: "injiq" },
      { id: '5-31', en: 'Courteous/polite', uz: "odobli" },
      { id: '5-32', en: 'Night owl', uz: "kechasi kech uxlaydigan odam" },
      { id: '5-33', en: 'Early bird', uz: "ertalab erta turadigan odam" },
      { id: '5-34', en: 'Look young for your age', uz: "yoshiga nisbatan yosh ko’rinmoq" },
      { id: '5-35', en: 'Bear a striking resemblance to', uz: "ga judayam o’xshamoq" },
      { id: '5-36', en: 'Good-looking', uz: "chiroyli, xushro’y" },
      { id: '5-37', en: 'Well-built', uz: "baquvvat" },
      { id: '5-38', en: 'Blonde hair', uz: "sariq soch" },
      { id: '5-39', en: 'Charismatic/attractive', uz: "jozibali" },
      { id: '5-40', en: '(low,high) self-esteem', uz: "o’ziga bo’lgan hurmat" }
    ]
  },
  {
    id: 'unit-6',
    title: 'Unit 6: Family',
    icon: '👪',
    words: [
      { id: '6-1', en: 'Nuclear family', uz: "kichik oila ( faqat ota-ona va bolalar bor oila)" },
      { id: '6-2', en: 'Extended family', uz: "katta oila ( bobo-buvi, amakilar ham bor oila)" },
      { id: '6-3', en: 'Dysfunctional family', uz: "og'ir oila ( namunasiz)" },
      { id: '6-4', en: 'Relative/kin', uz: "qarindosh" },
      { id: '6-5', en: 'Distant relative', uz: "uzoq qarindosh" },
      { id: '6-6', en: 'Descendant', uz: "davomchi, avlod" },
      { id: '6-7', en: 'Ancestor', uz: "ajdod" },
      { id: '6-8', en: 'Household', uz: "xo'jalik, oila xonadon" },
      { id: '6-9', en: 'Spouse', uz: "turmush o'rtoq" },
      { id: '6-10', en: 'Sibling', uz: "aka,uka,opa yoki singil" },
      { id: '6-11', en: 'Identical twins', uz: "o'xshash egizaklar" },
      { id: '6-12', en: 'An only child', uz: "yolg'iz farzand" },
      { id: '6-13', en: 'Mother-in-law', uz: "qaynona" },
      { id: '6-14', en: 'Father-in- law', uz: "qaynota" },
      { id: '6-15', en: 'Son-in-law', uz: "kuyov ( o'zingizning)" },
      { id: '6-16', en: 'Daughter-in-law', uz: "kelin ( o'zingizning)" },
      { id: '6-17', en: 'Brother-in-law', uz: "pochcha" },
      { id: '6-18', en: 'Sister-in-law', uz: "yanga" },
      { id: '6-19', en: 'Step', uz: "o'gay" },
      { id: '6-20', en: 'Stepmother', uz: "o'gay ona" },
      { id: '6-21', en: 'To start a family', uz: "oila qurmoq" },
      { id: '6-22', en: 'To give birth', uz: "bola tug'moq" },
      { id: '6-23', en: 'Offspring', uz: "bola, farzand" },
      { id: '6-24', en: 'To bring up ( a child)', uz: "ulg'aytirmoq, o'stirmoq" },
      { id: '6-25', en: 'Upbringing', uz: "tarbiya" },
      { id: '6-26', en: 'Breadwinner', uz: "oila boquvchi" },
      { id: '6-27', en: 'To adopt a child', uz: "bola asrab olmoq" },
      { id: '6-28', en: 'To foster', uz: "otaliqqa olmoq, qaramog'iga olmoq" },
      { id: '6-29', en: 'Overprotective parents', uz: "bolasini o'ta himoya qiladigan ota-onalar" },
      { id: '6-30', en: 'Spoilt child', uz: "tarbiyasi buzilgan, taltayib ketgan farzand" },
      { id: '6-31', en: 'Single parent', uz: "yolg'iz ota yoki ona" },
      { id: '6-32', en: 'Strict', uz: "qattiqqo'l" },
      { id: '6-33', en: 'generation gap', uz: "avlodlar o'rtasidagi farq" },
      { id: '6-34', en: 'hereditary', uz: "irsiy, avloddan avlodga o'tuvchi" },
      { id: '6-35', en: 'family gathering / family get-together', uz: "oilaviy yig'in" },
      { id: '6-36', en: 'close-knit family', uz: "ahil oila" },
      { id: '6-37', en: 'Widow/widower', uz: "beva ayol/erkak" },
      { id: '6-38', en: 'get on with / get along with', uz: "yaxshi chiqishmoq" },
      { id: '6-39', en: 'to fall out with / to have a falling out', uz: "arazlashmoq, urishib qolmoq" },
      { id: '6-40', en: 'spitting image', uz: "quyib qo'ygan nusxasi" },
      { id: '6-41', en: 'to follow in someone’s footsteps', uz: "birovning izidan yurmoq" },
      { id: '6-42', en: 'black sheep (of the family)', uz: "oilaga isnod olib kelgan oila azosi" }
    ]
  },
  {
    id: 'unit-7',
    title: 'Unit 7: Friends',
    icon: '🤝',
    words: [
      { id: '7-1', en: 'Keep in touch with friends', uz: "do'stlar aloqada bo'lmoq" },
      { id: '7-2', en: 'Lose touch with friends', uz: "do'stlar bilan aloqani uzmoq" },
      { id: '7-3', en: 'Drift apart (with)', uz: "uzoqlashmoq, uzoqlashib ketmoq" },
      { id: '7-4', en: 'Lifelong friend', uz: "bir umrlik do'st" },
      { id: '7-5', en: 'Hit it off', uz: "tezda til topishmoq" },
      { id: '7-6', en: 'Stick together through thick and thin', uz: "yaxshi-yomon kunlarda birga bo'lmoq, yelkadosh bo'lmoq" },
      { id: '7-7', en: 'Have a lot in common / have similar interests', uz: "ko'plab o'xshash jihatlari bor bo'lmoq" },
      { id: '7-8', en: 'A back stabber', uz: "ortdan pichoq uruvchi" },
      { id: '7-9', en: 'Vindictive', uz: "kek saqlovchi, gina saqlovchi" },
      { id: '7-10', en: 'Spiteful', uz: "ichi qora, xusumatli" },
      { id: '7-11', en: 'Shoulder to cry on', uz: "suyanchiq, dardkash" },
      { id: '7-12', en: 'Confide in', uz: "ishonmoq, suyanmoq" },
      { id: '7-13', en: 'Sympathetic', uz: "Hamdard, dilkash" },
      { id: '7-14', en: 'Respect your privacy', uz: "shaxsiy hayotingizni hurmat qilmoq" },
      { id: '7-15', en: 'Mentor', uz: "maslahatgo'y" },
      { id: '7-16', en: 'Inspiring', uz: "ruhlantiradigan, ilhombaxsh" },
      { id: '7-17', en: 'Gifted/talented', uz: "talantli" },
      { id: '7-18', en: 'Daredevil/risk-taker', uz: "tavakkalchi odam" },
      { id: '7-19', en: 'Don\'t see eye to eye', uz: "bir-birini tushunmaslik" },
      { id: '7-20', en: 'Fair-weather friend', uz: "faqat yaxshi kunlarda yoningda bo'ladigan do'st" },
      { id: '7-21', en: 'To have friends in high places', uz: "yuqori joylarda ishlaydigan do'stlari bo'lmoq" },
      { id: '7-22', en: 'a pal, a buddy (US) mate (UK)', uz: "do'st, og'ayni" },
      { id: '7-23', en: 'An acquaintance', uz: "tanish" },
      { id: '7-24', en: 'circle of friends', uz: "do'stlar davrasi" },
      { id: '7-25', en: 'bump into', uz: "to'satdan uchrashib qolmoq" },
      { id: '7-26', en: 'Count on/rely on', uz: "ishonmoq, suyanmoq" },
      { id: '7-27', en: 'Bestie/ best buddy', uz: "eng yaxshi do'st" },
      { id: '7-28', en: 'Make friends', uz: "do'stlashmoq, do'st topmoq" },
      { id: '7-29', en: 'to go in different directions / to lead separate lives', uz: "boshqa-boshqa yo'llardan bormoq" },
      { id: '7-30', en: 'To know someone inside out', uz: "birovni juda yaxshi bilmoq" }
    ]
  },
  {
    id: 'unit-8',
    title: 'Unit 8: Technology/TV',
    icon: '💻',
    words: [
      { id: '8-1', en: 'Technophile', uz: "texnologiyani xush ko’ruvchi odam" },
      { id: '8-2', en: 'Techie/tech-savvy', uz: "texnologiyalarni yaxshi biladigan odam" },
      { id: '8-3', en: 'Technophobe', uz: "texnologiyalardan qo’rquvchi odam" },
      { id: '8-4', en: 'cutting-edge', uz: "juda zamonaviy, so’nggi rusumdagi" },
      { id: '8-5', en: 'state-of-the-art', uz: "eng so’nggi rusumdagi" },
      { id: '8-6', en: 'advanced', uz: "rivojlangan, zamonaviy" },
      { id: '8-7', en: 'outdated/ obsolete', uz: "eskirgan, boshqa foydalanilmaydigan" },
      { id: '8-8', en: 'computer literate', uz: "kompyuter savodxonligi" },
      { id: '8-9', en: 'computer buff', uz: "kompyuter bilimdoni" },
      { id: '8-10', en: 'laptop', uz: "noutbuk" },
      { id: '8-11', en: 'PC (personal computer)', uz: "shaxshiy kompyuter" },
      { id: '8-12', en: 'to boot up', uz: "kompyuterni yoqmoq" },
      { id: '8-13', en: 'to crash', uz: "qotmoq" },
      { id: '8-14', en: 'to surf the internet', uz: "internetda qidirmoq" },
      { id: '8-15', en: 'viral', uz: "mashhur , trendda ( video,rasm va boshqalar)" },
      { id: '8-16', en: 'e-commerce', uz: "electron tijorat" },
      { id: '8-17', en: 'censorship', uz: "senzura, taqiq" },
      { id: '8-18', en: 'internet safety', uz: "internet xavfsizligi" },
      { id: '8-19', en: 'hacker', uz: "haker" },
      { id: '8-20', en: 'cyber', uz: "kiber" },
      { id: '8-21', en: 'cybersecurity', uz: "kiber xavfsizlik" },
      { id: '8-22', en: 'cybercrime', uz: "kiber jinoyat" },
      { id: '8-23', en: 'user-friendly', uz: "foydalanishga qulay" },
      { id: '8-24', en: 'AI (artificial intelligence)', uz: "suniy intellect" },
      { id: '8-25', en: 'To be glued to the screen', uz: "ekranga yopishib qolmoq" },
      { id: '8-26', en: 'Broadcast', uz: "efirga uzatmoq" },
      { id: '8-27', en: 'Commercial', uz: "reklama, e’lon" },
      { id: '8-28', en: 'Cheap source of entertainment', uz: "ko’ngil ochishning arzon manbasi" },
      { id: '8-29', en: 'Current affairs', uz: "dolzarb mavzular" },
      { id: '8-30', en: 'Propaganda', uz: "targ’ibot" },
      { id: '8-31', en: 'Sedentary lifestyle', uz: "kamharakat turmush tarsi" },
      { id: '8-32', en: 'A couch potato', uz: "ko’p tv ko’radigan odam" }
    ]
  },
  {
    id: 'unit-9',
    title: 'Unit 9: Books & Films',
    icon: '🎬',
    words: [
      { id: '9-1', en: 'Avid reader', uz: "ko’p kitob o’quvchi odam" },
      { id: '9-2', en: 'Fiction book', uz: "ilmiy kitob" },
      { id: '9-3', en: 'Non-fiction book', uz: "badiiy kitob" },
      { id: '9-4', en: 'Paperback/hardback', uz: "qog’oz muqovali/qattiq muqovali" },
      { id: '9-5', en: 'Plot', uz: "senariy, voqealar rivoji" },
      { id: '9-6', en: 'Page-turner', uz: "o’qiging sari o’qiging kelaveradigan" },
      { id: '9-7', en: 'Very readable', uz: "juda o’qishga arziydigan" },
      { id: '9-8', en: 'Engrossing', uz: "o’ziga rom etadigan" },
      { id: '9-9', en: 'Thought- provoking', uz: "o’ylantirib qo’yadigan" },
      { id: '9-10', en: 'Protagonist', uz: "ijobiy obraz" },
      { id: '9-11', en: 'Antagonist', uz: "salbiy obraz" },
      { id: '9-12', en: 'Highly recommended', uz: "ko’p tavsiya etiladigan" },
      { id: '9-13', en: 'Bestseller', uz: "ko’p sotilgan kitob" },
      { id: '9-14', en: 'Provide a window to the world', uz: "dunyoga oyna tutmoq" },
      { id: '9-15', en: 'Escape into another world', uz: "boshqa dunyoga qochmoq" },
      { id: '9-16', en: 'Broaden your knowledge', uz: "bilimingizni kengaytirmoq" },
      { id: '9-17', en: 'Strain on the eye', uz: "ko’zga bo’lgan bosim" },
      { id: '9-18', en: 'Worth seeing', uz: "ko’rishga arziydigan" },
      { id: '9-19', en: 'Dubbed', uz: "dublyaj qilingan" },
      { id: '9-20', en: 'Blockbuster', uz: "katta muvaffaqiyat qozongan film" },
      { id: '9-21', en: 'A big budget production', uz: "katta budjetli mahsulot" },
      { id: '9-22', en: 'Award-winning film', uz: "sovrindor film" },
      { id: '9-23', en: 'Lead role', uz: "bosh rol" },
      { id: '9-24', en: 'Star', uz: "bosh rolni ijro etmoq" },
      { id: '9-25', en: 'Totally believable performance', uz: "juda ishonarli ijro" },
      { id: '9-26', en: 'Favourite scene', uz: "sevimli sahna ( filmdagi qism)" },
      { id: '9-27', en: 'Based on real life', uz: "real hayotga asoslangan" },
      { id: '9-28', en: 'Predictable', uz: "oldindan nima bo’lishini biladigan, zerikarli ( film) ( Ahad Qayum production )" },
      { id: '9-29', en: 'Stunning visual effects', uz: "lol qoldiruvchi visual effektlar" },
      { id: '9-30', en: 'Memorable soundtrack', uz: "esda qolarli soundtrek" },
      { id: '9-31', en: 'Gripping', uz: "qiziqarli, etiborni o’ziga tortadigan ( film)" },
      { id: '9-32', en: 'Nail-biting', uz: "hayajonli, nima bo’lishi xavotirli ( film)" },
      { id: '9-33', en: 'Remake', uz: "qaytadan olingan film (e.g Romeo&Juliet)" },
      { id: '9-34', en: 'Sequel', uz: "film yoki kitobning keyingi qismi" },
      { id: '9-35', en: 'Extraterrestrial', uz: "o’zga sayyoradagi" },
      { id: '9-36', en: 'Premiere of the film', uz: "film premyerasi" },
      { id: '9-37', en: 'Not my cup of tea', uz: "mening qiziqishimga to’g’ri kelmaydi" },
      { id: '9-38', en: 'Mimic bad behaviour', uz: "yomon xulqni o’zlashtirmoq" },
      { id: '9-39', en: 'Time consuming', uz: "ko’p vaqt oladigan" },
      { id: '9-40', en: 'Superficial', uz: "yuzaki ( again Ahad Qayum Production)" },
      { id: '9-41', en: 'Bedtime reading', uz: "uyqudan oldingi mutolaa" },
      { id: '9-42', en: 'Tear-jerking', uz: "yig’latuvchi" },
      { id: '9-43', en: '(Read)From cover to cover', uz: "boshidan oxirigacha ( kitobning)" }
    ]
  },
  {
    id: 'unit-10',
    title: 'Unit 10: Food & Cooking',
    icon: '🍲',
    words: [
      { id: '10-1', en: 'Favourite dish', uz: "sevimli ovqat" },
      { id: '10-2', en: 'Delicacy', uz: "noyob taom" },
      { id: '10-3', en: 'Dine out', uz: "tashqarida ovqatlanmoq" },
      { id: '10-4', en: 'Staple food', uz: "eng ko'p yeyiladigan ovqat" },
      { id: '10-5', en: 'Delicious/delectable/yummy/mouth-watering', uz: "mazali" },
      { id: '10-6', en: 'Terrific flavour', uz: "rasvo tam" },
      { id: '10-7', en: 'Lovely aroma', uz: "xushbo’y hid" },
      { id: '10-8', en: 'Nutritious', uz: "to’yimli" },
      { id: '10-9', en: 'Have a healthy diet', uz: "sog’lom ovqatlanmoq" },
      { id: '10-10', en: 'Home-cooked food', uz: "uyda qilingan ovqat" },
      { id: '10-11', en: 'Vegan', uz: "vegetarian" },
      { id: '10-12', en: 'Fussy eater', uz: "chimxo’r" },
      { id: '10-13', en: 'Wide menu', uz: "keng menyu" },
      { id: '10-14', en: 'Beverage', uz: "ichimlik" },
      { id: '10-15', en: 'Season', uz: "tuzlamoq, tuz qo’shmoq" },
      { id: '10-16', en: 'Greasy/fatty', uz: "yog’li, moyli" },
      { id: '10-17', en: 'Overeating', uz: "keragidan ko’p ovqat yemoq" },
      { id: '10-18', en: 'Food poisoning', uz: "ovqatdan zaharlanish" },
      { id: '10-19', en: 'Obese', uz: "semiz" },
      { id: '10-20', en: 'Overcooked', uz: "ko’p pishirib yuborilgan" },
      { id: '10-21', en: 'Underdone', uz: "keragidan kam pishirilgan, xom" },
      { id: '10-22', en: 'Grab a bite to eat', uz: "bir tishlam yeb olmoq" },
      { id: '10-23', en: 'Have a sweet tooth', uz: "shirinxo’r, shirinlik ko’p yeyuvchi" },
      { id: '10-24', en: 'Tuck in/into', uz: "ko’p yemoq, paqqos tushirmoq" },
      { id: '10-25', en: 'Comfort food', uz: "siqilganda kayfiyatni ko’tarish uchun yeyiladigan taom" },
      { id: '10-26', en: 'Processed food', uz: "qayta ishlangan ovqat ( muzlatilgan, konservalangan va hokazo)" },
      { id: '10-27', en: 'Cuisine', uz: "oshxona,ovqat ( Italian cuisine)" },
      { id: '10-28', en: 'Ready meal', uz: "tayyor ovqat (oldindan tayyorlangan)" },
      { id: '10-29', en: 'Restrain one’s hunger', uz: "nafsini tiymoq (ovqatlanmaslik)" },
      { id: '10-30', en: 'Takeaway', uz: "olib ketish uchun tayyorlangan ovqat" },
      { id: '10-31', en: 'To be dying of hunger', uz: "juda och qolmoq" },
      { id: '10-32', en: 'To be full-up', uz: "judayam to’yib ketmoq" },
      { id: '10-33', en: 'Bolt something down', uz: "paqqos tushirmoq, yamlamay yutmoq" },
      { id: '10-34', en: 'To eat like a horse', uz: "juda ko’p ovqat yemoq" },
      { id: '10-35', en: 'To spoil appetite', uz: "ishtahani buzmoq" }
    ]
  },
  {
    id: 'unit-11',
    title: 'Unit 11: Holidays & Tourism',
    icon: '✈️',
    words: [
      { id: '11-1', en: 'All-in package holiday', uz: "barcha xizmatlar uchun oldindan birdaniga to’lanadigan turistik sayohat" },
      { id: '11-2', en: 'Breathtaking view', uz: "maftunkor manzara" },
      { id: '11-3', en: 'To get away from it all', uz: "normal hayot tarzidan qochmoq" },
      { id: '11-4', en: 'Guided tour', uz: "gid boshqarib boradigan sayohat" },
      { id: '11-5', en: 'Holiday destination', uz: "tatil manzili" },
      { id: '11-6', en: 'Holiday of a lifetime', uz: "bir umrga tatiydigan sayohat" },
      { id: '11-7', en: 'Holiday resort', uz: "dam olish joyi ( ko’pchilik boradigan )" },
      { id: '11-8', en: 'Hordes of tourists', uz: "turistlar galasi,to’dasi" },
      { id: '11-9', en: 'Local crafts', uz: "mahalliy hunarmandchilik mahsulotlari" },
      { id: '11-10', en: 'Out of season', uz: "mavsumdan tashqari" },
      { id: '11-11', en: 'Places of interest', uz: "turistlarga qiziq bo’lgan joylar" },
      { id: '11-12', en: 'To go sightseeing', uz: "diqqatga sazovor joylarni tomosha qilishga bormoq" },
      { id: '11-13', en: 'Tourist trap', uz: "sayyohlar bilan gavjum joy" },
      { id: '11-14', en: 'Affordable destinations', uz: "cho’ntakbop sayohat manzillari" },
      { id: '11-15', en: 'Affordable travel', uz: "cho’ntakbop sayohat" },
      { id: '11-16', en: 'Magnificent landscapes', uz: "maftunkor manzaralar" },
      { id: '11-17', en: 'Scenic views', uz: "go’zal manzaralar" },
      { id: '11-18', en: 'Self-catering accommodation', uz: "o’zingiz ovqat tayyorlaydigan turar joy ( sayohatda)" },
      { id: '11-19', en: 'Stunning architecture', uz: "muhtasham arxitektura" },
      { id: '11-20', en: 'Travel light', uz: "kam yuk bilan sayohat qilmoq" },
      { id: '11-21', en: 'Off the beaten track', uz: "odamlardan yiroqda, chetroq joydagi" },
      { id: '11-22', en: 'Long-haul flight', uz: "uzoq davom etuvchi parvoz" },
      { id: '11-23', en: 'Swarmed with tourists', uz: "turistlar bilan to’lib toshgan" },
      { id: '11-24', en: 'Exotic destination', uz: "qiziq,antiqa manzil" },
      { id: '11-25', en: 'Spectacular', uz: "ko’z yayraydigan, kuchli taassurot qoldiradigan" },
      { id: '11-26', en: 'Lush forest', uz: "o’simliklarga boy o’rmon" },
      { id: '11-27', en: 'Good value for money', uz: "narxiga arziydigan" },
      { id: '11-28', en: 'Broaden horizons', uz: "dunyoqarashni kengaytirmoq" },
      { id: '11-29', en: 'Wander streets', uz: "ko’chalarni kezmoq" },
      { id: '11-30', en: 'Customer service', uz: "mijozga xizmat ko’rstaish" }
    ]
  },
  {
    id: 'unit-12',
    title: 'Unit 12: Social Problems',
    icon: '🌍',
    words: [
      { id: '12-1', en: 'Daunting problem', uz: "qo'rqinchli, xavotirga soladigan muammo" },
      { id: '12-2', en: 'Complex issue', uz: 'murakkab masala, muammo' },
      { id: '12-3', en: 'Ongoing problem', uz: 'davom etayotgan muammo' },
      { id: '12-4', en: 'Unresolved problem', uz: 'yechilmagan muammo' },
      { id: '12-5', en: 'Pervasive problem', uz: 'keng tarqalgan muammo' },
      { id: '12-6', en: 'A burden on society', uz: "jamiyat uchun og'ir yuk" },
      { id: '12-7', en: 'A heated debate', uz: "qizg'in munozara" },
      { id: '12-8', en: 'Third world countries', uz: 'rivojlanmagan davlatlar' },
      { id: '12-9', en: 'Gap between rich and poor', uz: "boy va kambag'allar farqi" },
      { id: '12-10', en: 'Social inequality', uz: 'ijtimoiy tengsizlik' },
      { id: '12-11', en: 'Racial discrimination', uz: 'irqiy ayirmachilik' },
      { id: '12-12', en: 'Racism', uz: 'irqchilik' },
      { id: '12-13', en: 'Domestic violence', uz: "oilaviy zo'ravonlik" },
      { id: '12-14', en: 'Juvenile delinquency', uz: 'voyaga yetmaganlar jinoyatchiligi' },
      { id: '12-15', en: 'Political unrest', uz: 'siyosiy notinchlik, tartibsizliklar' },
      { id: '12-16', en: 'Brain drain', uz: "aqllar oqimi, mutaxassislarning chetga ko'chib ketishi" },
      { id: '12-17', en: 'Rising cost of living', uz: 'yashash xarajati oshishi' },
      { id: '12-18', en: 'Impoverished neighbourhood', uz: 'qashshoq mahalla, nochor hudud' },
      { id: '12-19', en: 'Run-down area', uz: 'xarobaga aylangan hudud' },
      { id: '12-20', en: 'Breakdown of families', uz: 'oilalar buzilishi' },
      { id: '12-21', en: 'Despair', uz: 'umidsizlik' },
      { id: '12-22', en: 'Address the problem', uz: "muammoga e'tibor qaratmoq, hal qilishga kirishmoq" },
      { id: '12-23', en: 'Tackle the problem', uz: 'muammoni hal qilish, kurashish' },
      { id: '12-24', en: 'Take action', uz: "chora ko'rmoq" },
      { id: '12-25', en: 'Leave things as they are', uz: "o'z holiga tashlab qo'ymoq" },
      { id: '12-26', en: 'Social welfare', uz: 'ijtimoiy farovonlik' },
      { id: '12-27', en: 'Social security', uz: 'ijtimoiy xavfsizlik' },
      { id: '12-28', en: 'Long-term measures', uz: 'uzoq muddatli choralar' },
      { id: '12-29', en: 'New/novel solutions', uz: 'yangi yechimlar' },
      { id: '12-30', en: 'The elite', uz: 'elita qatlam' },
      { id: '12-31', en: 'Distrust to the government', uz: "hukumatga bo'lgan ishonchsizlik" },
      { id: '12-32', en: 'Hatred', uz: 'nafrat' },
      { id: '12-33', en: 'Civilians', uz: 'tinch aholi' },
      { id: '12-34', en: 'Transparency', uz: 'shaffoflik, ochiqlik' },
      { id: '12-35', en: 'Low-income household', uz: 'kam daromadli oila' },
      { id: '12-36', en: 'Cut expenses', uz: 'xarajatlarni kamaytirmoq' },
      { id: '12-37', en: 'Overpopulation', uz: 'aholi zichligi, aholining haddan tashqari ko\'payishi' },
      { id: '12-38', en: 'Death-sentence', uz: "o'lim jazosi" },
      { id: '12-39', en: 'Detrimental', uz: 'zararli' },
      { id: '12-40', en: 'Intervention', uz: 'aralashuv, davlat aralashuvi' }
    ]
  },
  {
    id: 'unit-13',
    title: 'Unit 13: Buildings',
    icon: '🏢',
    words: [
      { id: '13-1', en: 'Façade', uz: 'binoning old qismi' },
      { id: '13-2', en: 'Landmark', uz: 'ko’zga ko’ringan bino, mo’ljal' },
      { id: '13-3', en: 'Concrete', uz: 'beton' },
      { id: '13-4', en: 'reinforced concrete', uz: 'temir beton' },
      { id: '13-5', en: 'timber', uz: 'yog’och' },
      { id: '13-6', en: 'Marble', uz: 'marmar' },
      { id: '13-7', en: 'Sky-scraper', uz: 'osmono’par bino' },
      { id: '13-8', en: 'Warehouse', uz: 'omborxona' },
      { id: '13-9', en: 'a ruin', uz: 'xaroba' },
      { id: '13-10', en: 'column', uz: 'ustun' },
      { id: '13-11', en: 'Steeple', uz: 'uchli minora' },
      { id: '13-12', en: 'Dome', uz: 'gumbaz' },
      { id: '13-13', en: 'eye-catching', uz: 'jozibador, o’ziga tortadigan' },
      { id: '13-14', en: 'ornate', uz: 'bezamoq' },
      { id: '13-15', en: 'iconic', uz: 'juda mashhur' },
      { id: '13-16', en: 'spacious', uz: 'keng' },
      { id: '13-17', en: 'ugly / unsightly', uz: 'ko’rimsiz, xunuk' },
      { id: '13-18', en: 'eyesore', uz: 'ko’rimsiz' },
      { id: '13-19', en: 'fall into disrepair', uz: 'vayrona holiga kelib qolgan' },
      { id: '13-20', en: 'past its heyday', uz: 'urfdan qolgan, ortiq mashhur emas' },
      { id: '13-21', en: 'maintain', uz: 'yaxshi holatda saqlamoq' },
      { id: '13-22', en: 'energy efficient', uz: 'energiya samarador' },
      { id: '13-23', en: 'double glazing', uz: 'ikki qavatli oyna' },
      { id: '13-24', en: 'wheelchair friendly', uz: 'nogiron insonlar uchun qulay' },
      { id: '13-25', en: 'Exterior', uz: 'binoning tashqi qismi' },
      { id: '13-26', en: 'Interior', uz: 'binoning ichki qismi' },
      { id: '13-27', en: 'Blueprint', uz: 'bino chizmasi' },
      { id: '13-28', en: 'planning permission', uz: 'qurilishga ruxsatnoma' },
      { id: '13-29', en: 'building site', uz: 'qurilish bo’layotgan joy' },
      { id: '13-30', en: 'to construct', uz: 'qurmoq' }
    ]
  },
  {
    id: 'unit-14',
    title: 'Unit 14: Transport',
    icon: '🚌',
    words: [
      { id: '14-1', en: 'a means / form of transportation', uz: 'transport turi' },
      { id: '14-2', en: 'lane', uz: 'yo‘lak' },
      { id: '14-3', en: 'cycle lane', uz: 'velosiped yo‘li' },
      { id: '14-4', en: 'bypass / ring road / beltway', uz: 'halqa yo‘li' },
      { id: '14-5', en: 'freeway / highway / expressway', uz: 'katta yo‘l, shosse, trassa' },
      { id: '14-6', en: 'motorway (UK)', uz: 'shosse' },
      { id: '14-7', en: 'overpass', uz: 'estakada, yo‘l ustidagi ko‘prik' },
      { id: '14-8', en: 'junction', uz: 'chorraha, yo‘l kesishgan joy' },
      { id: '14-9', en: 'roundabout', uz: 'aylanma yo‘l' },
      { id: '14-10', en: 'traffic light', uz: 'svetafor' },
      { id: '14-11', en: 'traffic jam', uz: 'tirbandlik, probka' },
      { id: '14-12', en: 'to be caught in traffic / a traffic jam', uz: 'tirbandlikda qolmoq' },
      { id: '14-13', en: 'to get stuck in traffic / a traffic jam', uz: 'tirbandlikda qolmoq' },
      { id: '14-14', en: 'heavy traffic', uz: 'katta tirbandlik' },
      { id: '14-15', en: 'roadworks', uz: 'yo‘l ta’mirlash ishlari' },
      { id: '14-16', en: 'diversion', uz: 'aylanib o‘tish yo‘li (yo‘l yopilganda)' },
      { id: '14-17', en: 'to be held up', uz: 'yo‘lda ushlanib qolmoq (avariya, tirbandlik sababli)' },
      { id: '14-18', en: 'bottleneck', uz: 'tirbandlik' },
      { id: '14-19', en: 'speed limit', uz: 'tezlik limiti' },
      { id: '14-20', en: 'road accident', uz: 'avariya' },
      { id: '14-21', en: 'to commute', uz: 'ishga, o‘qishga qatnamoq' },
      { id: '14-22', en: 'rush hour', uz: 'tig‘iz payt' },
      { id: '14-23', en: 'the outskirts', uz: 'shahar tashqarisi' },
      { id: '14-24', en: 'rail network', uz: 'temiryo‘l tarmog‘i' },
      { id: '14-25', en: 'the underground / the tube / the subway / the metro', uz: 'metro' },
      { id: '14-26', en: 'shuttle', uz: 'yo‘lovchilarni olib yuruvchi transport' },
      { id: '14-27', en: 'gas guzzler (informal)', uz: 'ko‘p yoqilg‘i yeydigan transport' },
      { id: '14-28', en: 'autonomous vehicle / driverless car / self-driving car', uz: 'haydovchisiz mashina' },
      { id: '14-29', en: 'space travel', uz: 'fazoga sayohat' },
      { id: '14-30', en: 'high-speed rail', uz: 'tezyurar poyezd' },
      { id: '14-31', en: 'pedestrian', uz: 'piyoda' },
      { id: '14-32', en: 'to run a car', uz: 'mashina egasi bo‘lib yurmoq' },
      { id: '14-33', en: 'toll', uz: 'pullik yo‘l' },
      { id: '14-34', en: 'a speeding fine', uz: 'tezlikni oshirgani uchun jarima' },
      { id: '14-35', en: 'bumper to bumper', uz: 'bir-biriga juda yaqin (mashinalar)' },
      { id: '14-36', en: 'beat the traffic', uz: 'tirbandlikdan qochmoq (juda erta yo‘lga chiqib)' },
      { id: '14-37', en: 'hit the road', uz: 'yo‘lga tushmoq' },
      { id: '14-38', en: 'hitch a lift / ride', uz: 'o‘tkinchi mashinada ketmoq' }
    ]
  },
  {
    id: 'unit-15',
    title: 'Unit 15: Health',
    icon: '🏥',
    words: [
      { id: '15-1', en: 'health problems (or health issues)', uz: 'sog‘liqdagi muammolar' },
      { id: '15-2', en: 'a healthy lifestyle (or unhealthy lifestyle)', uz: 'sog‘lom turmush tarzi' },
      { id: '15-3', en: 'healthcare', uz: 'sog‘liqni saqlash' },
      { id: '15-4', en: 'health-conscious', uz: 'sog‘lig‘iga e’tibor beruvchi' },
      { id: '15-5', en: 'health benefit', uz: 'sog‘liq uchun foyda' },
      { id: '15-6', en: 'mental health', uz: 'ruhiy sog‘liq' },
      { id: '15-7', en: 'to look after your health / to take care of your health', uz: 'sog‘lig‘iga g‘amxo‘rlik qilmoq' },
      { id: '15-8', en: 'to regain your health', uz: 'sog‘lig‘ini tiklamoq' },
      { id: '15-9', en: 'to be unfit', uz: 'nosog‘lom bo‘lmoq' },
      { id: '15-10', en: 'prevent', uz: 'oldini olmoq' },
      { id: '15-11', en: 'in good shape', uz: 'yaxshi holatda, badani baquvvat' },
      { id: '15-12', en: 'out of shape', uz: 'yaxshi holatda emas (juda semiz yoki ozg‘in)' },
      { id: '15-13', en: 'get back into shape', uz: 'formaga qaytmoq' },
      { id: '15-14', en: 'work out', uz: 'shug‘ullanmoq (zalda)' },
      { id: '15-15', en: 'comfort food', uz: 'tushkun paytda kayfiyatni ko‘tarish uchun yeyiladigan ovqat' },
      { id: '15-16', en: 'portion', uz: 'porsiya' },
      { id: '15-17', en: 'addictive', uz: 'qo‘shimcha (o‘rganib qolishga olib keladigan)' },
      { id: '15-18', en: 'nutrients', uz: 'ozuqaviy moddalar' },
      { id: '15-19', en: 'binge drinking', uz: 'ko‘p ichish' },
      { id: '15-20', en: 'you are what you eat', uz: 'nima yisang o‘shasan' },
      { id: '15-21', en: 'overweight', uz: 'semiz' },
      { id: '15-22', en: 'obesity', uz: 'semizlik' },
      { id: '15-23', en: 'diabetes', uz: 'qand kasalligi' },
      { id: '15-24', en: 'overeating', uz: 'keragidan ko‘p yeyish' },
      { id: '15-25', en: 'fall ill', uz: 'kasal bo‘lmoq' },
      { id: '15-26', en: 'come down with (something)', uz: 'kasal bo‘lmoq' },
      { id: '15-27', en: 'get over (when related to health)', uz: 'sog‘aymoq' },
      { id: '15-28', en: 'to be under the weather', uz: 'o‘zini yaxshi his qilmaslik' },
      { id: '15-29', en: 'back on your feet', uz: 'oyoqqa turmoq (tuzalib ketish)' },
      { id: '15-30', en: 'to make a speedy recovery', uz: 'tez sog‘aymoq' },
      { id: '15-31', en: 'fit as a fiddle', uz: 'juda sog‘lom' },
      { id: '15-32', en: 'GP (general practitioner)', uz: 'oilaviy shifokor' },
      { id: '15-33', en: 'a check-up', uz: 'tibbiy tekshiruv' },
      { id: '15-34', en: 'prescription', uz: 'shifokor yozuvi (dori uchun)' },
      { id: '15-35', en: 'phone in sick', uz: 'ish joyga kasalligini bildirib qo‘ng‘iroq qilmoq' },
      { id: '15-36', en: 'to catch a cold', uz: 'shamollamoq' },
      { id: '15-37', en: 'a runny nose', uz: 'oqayotgan burun' },
      { id: '15-38', en: 'a blocked nose', uz: 'yopilib qolgan burun' },
      { id: '15-39', en: 'to vomit', uz: 'qayt qilmoq' },
      { id: '15-40', en: 'cuts and bruises', uz: 'yara-chaqalar (kichik jarohatlar)' }
    ]
  },
  {
    id: 'unit-16',
    title: 'Unit 16: Weather',
    icon: '🌤️',
    words: [
      { id: '16-1', en: 'fair', uz: '(adolatli, yaxshi ob-havo)' },
      { id: '16-2', en: 'snowflake', uz: 'qor parchasi' },
      { id: '16-3', en: 'heavy snow', uz: 'kuchli qor yog‘ishi' },
      { id: '16-4', en: 'blizzard', uz: 'bo‘ron, qor bo‘roni' },
      { id: '16-5', en: 'avalanche', uz: 'qor ko‘chishi' },
      { id: '16-6', en: 'freezing / bitterly cold', uz: 'juda sovuq' },
      { id: '16-7', en: 'hail', uz: 'do‘l' },
      { id: '16-8', en: 'to dress up warm', uz: 'qalin kiyinmoq' },
      { id: '16-9', en: 'to melt', uz: 'erimoq' },
      { id: '16-10', en: 'heavy rain', uz: 'kuchli yomg‘ir' },
      { id: '16-11', en: 'torrential rain', uz: 'shamsa yomg‘ir (juda kuchli)' },
      { id: '16-12', en: 'to pour', uz: 'yomg‘ir quyib yog‘moq' },
      { id: '16-13', en: 'raining cats and dogs', uz: 'juda kuchli yomg‘ir yog‘moq' },
      { id: '16-14', en: 'to get drenched / soaked', uz: 'shalabbo bo‘lmoq' },
      { id: '16-15', en: 'drizzle', uz: 'mayin yomg‘ir' },
      { id: '16-16', en: 'gentle rain', uz: 'mayin yomg‘ir' },
      { id: '16-17', en: 'to get caught in the rain', uz: 'yomg‘irda qolib ketmoq' },
      { id: '16-18', en: 'to be rained off', uz: 'yomg‘ir tufayli bekor bo‘lmoq' },
      { id: '16-19', en: 'to clear up', uz: 'havo ochilmoq (yomg‘irdan keyin)' },
      { id: '16-20', en: 'puddle', uz: 'ko‘lmak' },
      { id: '16-21', en: 'foul weather', uz: 'yomon ob-havo' },
      { id: '16-22', en: 'to come out (the sun)', uz: 'quyosh chiqmoq' },
      { id: '16-23', en: 'baking hot / boiling hot', uz: 'juda issiq' },
      { id: '16-24', en: 'drought', uz: 'qurg‘oqchilik' },
      { id: '16-25', en: 'humid / humidity', uz: 'namlik' },
      { id: '16-26', en: 'sweltering', uz: 'juda issiq (dim)' },
      { id: '16-27', en: 'glorious weather', uz: 'ajoyib ob-havo' },
      { id: '16-28', en: 'fine weather', uz: 'yaxshi ob-havo' },
      { id: '16-29', en: 'clear blue skies', uz: 'bulutsiz ochiq osmon' },
      { id: '16-30', en: 'overcast', uz: 'bulutli' },
      { id: '16-31', en: 'freak weather conditions', uz: 'g‘ayrioddiy ob-havo sharoitlari' },
      { id: '16-32', en: 'mild weather', uz: 'iliq ob-havo' },
      { id: '16-33', en: 'in all weathers', uz: 'har qanday ob-havoda' },
      { id: '16-34', en: 'to save for a rainy day', uz: 'qiyin kunlar uchun saqlamoq' },
      { id: '16-35', en: 'come rain or shine', uz: 'har qanday holatda ham' },
      { id: '16-36', en: 'every cloud has a silver lining', uz: 'har yomonning bir yaxshisi bor' },
      { id: '16-37', en: 'on cloud nine', uz: 'juda xursand bo‘lmoq' },
      { id: '16-38', en: 'ray of hope', uz: 'umid uchquni' },
      { id: '16-39', en: 'out of the blue', uz: 'to‘satdan' },
      { id: '16-40', en: 'to break the ice', uz: 'suhbat boshlamoq' },
      { id: '16-41', en: 'tip of the iceberg', uz: 'katta muammoning kichik qismi' },
      { id: '16-42', en: 'to be snowed under', uz: 'juda band bo‘lmoq' },
      { id: '16-43', en: 'storm in a teacup', uz: 'kichik narsani kattalashtirish' },
      { id: '16-44', en: 'fair-weather friend', uz: 'faqat yaxshi paytda yoningda bo‘ladigan do‘st' }
    ]
  },
  {
    id: 'unit-17',
    title: 'Unit 17: Environment',
    icon: '🌍',
    words: [
      { id: '17-1', en: 'environmentalist', uz: 'atrof-muhit himoyachisi' },
      { id: '17-2', en: 'environmentally-friendly', uz: 'tabiatga zarar yetkazmaydigan' },
      { id: '17-3', en: 'environmental hazard', uz: 'tabiat uchun xavf' },
      { id: '17-4', en: 'conservationist', uz: 'tabiatni asrovchi (insonlardan)' },
      { id: '17-5', en: 'species', uz: 'tur (o‘simlik yoki hayvon)' },
      { id: '17-6', en: 'endangered species', uz: 'yo‘qolib borayotgan turlar' },
      { id: '17-7', en: 'rare species', uz: 'kamyob turlar' },
      { id: '17-8', en: 'extinct species', uz: 'yo‘qolib ketgan turlar' },
      { id: '17-9', en: 'biodiversity', uz: 'bioxilma-xillik' },
      { id: '17-10', en: 'loss of biodiversity', uz: 'bioxilma-xillikning yo‘qolishi (turlarning kamayishi)' },
      { id: '17-11', en: 'habitat', uz: 'yashash joyi (hayvon, o‘simliklarning)' },
      { id: '17-12', en: 'to inhabit', uz: 'yashamoq' },
      { id: '17-13', en: 'marine', uz: 'suvga oid' },
      { id: '17-14', en: 'nocturnal', uz: 'tungi (tunda aktiv)' },
      { id: '17-15', en: 'extinction', uz: 'yo‘qolib ketish, qirilib ketish (o‘simlik, hayvonlarning)' },
      { id: '17-16', en: 'combat climate change', uz: 'iqlim o‘zgarishini to‘xtatish' },
      { id: '17-17', en: 'ozone layer', uz: 'ozon qatlami' },
      { id: '17-18', en: 'erosion', uz: 'yemirilish' },
      { id: '17-19', en: 'soil erosion', uz: 'tuproq yemirilishi' },
      { id: '17-20', en: 'deforestation', uz: 'o‘rmonlarning yo‘qolib ketishi' },
      { id: '17-21', en: 'logging', uz: 'daraxtlarni kesish' },
      { id: '17-22', en: 'to fight / combat / tackle global warming', uz: 'global isishga qarshi kurashmoq' },
      { id: '17-23', en: 'dumping ground', uz: 'axlat to‘kiladigan joy' },
      { id: '17-24', en: 'acid rain', uz: 'kislotali yomg‘ir' },
      { id: '17-25', en: 'to contaminate', uz: 'ifloslantirmoq, zaharlamoq' },
      { id: '17-26', en: 'toxic / poisonous', uz: 'zaharli' },
      { id: '17-27', en: 'poaching', uz: 'brakonerlik' },
      { id: '17-28', en: 'to recycle', uz: 'qayta ishlamoq' },
      { id: '17-29', en: 'solar power', uz: 'quyosh energiyasi' },
      { id: '17-30', en: 'afforestation', uz: 'o‘rmonlashtirish (daraxt ekish orqali)' },
      { id: '17-31', en: 'safeguard', uz: 'himoya qilmoq' },
      { id: '17-32', en: 'energy-efficient', uz: 'energiya tejovchi' }
    ]
  },
  {
    id: 'unit-18',
    title: 'Unit 18: Sports',
    icon: '⚽',
    words: [
      { id: '18-1', en: 'extreme sport', uz: 'ekstremal sport' },
      { id: '18-2', en: 'to keep fit', uz: 'o‘zini sog‘lom saqlamoq' },
      { id: '18-3', en: 'strenuous exercise', uz: 'charchatuvchi, og‘ir mashq' },
      { id: '18-4', en: 'to get into shape', uz: 'sog‘lomlashmoq' },
      { id: '18-5', en: 'to warm up', uz: 'qizib olmoq (mashqdan oldin)' },
      { id: '18-6', en: 'to be out of condition', uz: 'jismoniy formada bo‘lmaslik' },
      { id: '18-7', en: 'pitch', uz: 'maydon (futbol, kriket kabi sport turlari uchun)' },
      { id: '18-8', en: 'changing room', uz: 'kiyim almashtirish xonasi' },
      { id: '18-9', en: 'competitor', uz: 'raqib' },
      { id: '18-10', en: 'a personal best', uz: 'shaxsiy rekord' },
      { id: '18-11', en: 'to set a record', uz: 'rekord qo‘ymoq' },
      { id: '18-12', en: 'to break a record', uz: 'rekordni buzmoq' },
      { id: '18-13', en: 'kit', uz: 'sport kiyimi (futbolka)' },
      { id: '18-14', en: 'a home game', uz: 'uydagi o‘yin' },
      { id: '18-15', en: 'an away game', uz: 'mehmondagi o‘yin' },
      { id: '18-16', en: 'supporter', uz: 'muxlis' },
      { id: '18-17', en: 'contest', uz: 'musobaqa' },
      { id: '18-18', en: 'championship', uz: 'chempionat' },
      { id: '18-19', en: 'versus (vs)', uz: 'qarshi' },
      { id: '18-20', en: 'to compete', uz: 'musobaqada qatnashmoq' },
      { id: '18-21', en: 'competitive', uz: 'raqobatbardosh' },
      { id: '18-22', en: 'to score', uz: 'gol urmoq' },
      { id: '18-23', en: 'the score', uz: 'hisob' },
      { id: '18-24', en: 'a draw', uz: 'durang' },
      { id: '18-25', en: 'reserve', uz: 'zaxiradagi o‘yinchi' },
      { id: '18-26', en: 'a season ticket', uz: 'mavsumiy chipta' },
      { id: '18-27', en: 'amateur', uz: 'havaskor' },
      { id: '18-28', en: 'professional', uz: 'professional' },
      { id: '18-29', en: 'to blow away the competition', uz: 'raqibni oson yengmoq' },
      { id: '18-30', en: 'front-runner', uz: 'favorit (yutishga asosiy da’vogar)' },
      { id: '18-31', en: 'to get a second wind', uz: 'yana kuchga kirish' },
      { id: '18-32', en: 'underdog', uz: 'autsayder (eng kuchsiz ishtirokchi)' }
    ]
  },
  {
    id: 'unit-19',
    title: 'Unit 19: Shopping',
    icon: '🛍️',
    words: [
      { id: '19-1', en: 'to do the shopping', uz: 'xarid qilmoq' },
      { id: '19-2', en: 'goods', uz: 'mahsulotlar' },
      { id: '19-3', en: 'shop around', uz: 'bozor aylanmoq (narxlarni taqqoslash uchun)' },
      { id: '19-4', en: 'retail therapy', uz: 'xarid terapiyasi (kayfiyatni ko‘tarish uchun xarid qilish)' },
      { id: '19-5', en: 'to go on a shopping spree', uz: 'katta miqdorda ko‘p narsa xarid qilmoq' },
      { id: '19-6', en: 'a shopaholic', uz: 'ko‘p xarid qiluvchi odam' },
      { id: '19-7', en: 'to try on', uz: 'kiyib ko‘rmoq' },
      { id: '19-8', en: 'take something back', uz: 'do‘konga qaytarib bermoq' },
      { id: '19-9', en: 'to return an item', uz: 'sotib olingan narsani qaytarmoq' },
      { id: '19-10', en: 'for sale', uz: 'sotuvga qo‘yilgan' },
      { id: '19-11', en: 'shopping list', uz: 'xarid qilinadigan narsalar ro‘yxati' },
      { id: '19-12', en: 'to give someone the hard sell', uz: 'biror narsani olishga majbur qilmoq' },
      { id: '19-13', en: 'shoplifter', uz: 'do‘kondan o‘maruvchi' },
      { id: '19-14', en: 'to order', uz: 'buyurtma qilmoq' },
      { id: '19-15', en: 'shop assistant / sales assistant', uz: 'sotuvchi' },
      { id: '19-16', en: 'cashier', uz: 'kassir' },
      { id: '19-17', en: 'market trader / market vendor', uz: 'bozor sotuvchisi' },
      { id: '19-18', en: 'shop / store / retail outlet', uz: 'do‘kon' },
      { id: '19-19', en: 'department store', uz: 'univermaq' },
      { id: '19-20', en: 'convenience store', uz: 'kichik kechayu kunduz ochiq do‘kon' },
      { id: '19-21', en: 'greengrocer', uz: 'ko‘kat sotuvchi' },
      { id: '19-22', en: 'butcher', uz: 'qassob' },
      { id: '19-23', en: 'fishmonger', uz: 'baliq sotuvchi' },
      { id: '19-24', en: 'chemist (UK) / drugstore (US)', uz: 'dorixona' },
      { id: '19-25', en: 'DIY store', uz: 'uy qurilish materiallari sotiladigan do‘kon' },
      { id: '19-26', en: 'hardware shop', uz: 'temir-tersak do‘koni' },
      { id: '19-27', en: 'flea market', uz: 'yorma bozor' },
      { id: '19-28', en: 'shopping mall', uz: 'savdo markazi' },
      { id: '19-29', en: 'on sale / on offer', uz: 'chegirmada' },
      { id: '19-30', en: 'to pick up a bargain / to snap up a bargain', uz: 'arzon narsani tez sotib olmoq' },
      { id: '19-31', en: 'to splash out', uz: 'ko‘p pul sarflamoq' },
      { id: '19-32', en: 'to be value for money', uz: 'puliga arziydigan' },
      { id: '19-33', en: 'overpriced', uz: 'juda qimmat narxlangan' },
      { id: '19-34', en: 'underpriced', uz: 'arzon narxlangan' },
      { id: '19-35', en: 'queue', uz: 'navbat' },
      { id: '19-36', en: 'checkout', uz: 'kassa (supermarketda)' },
      { id: '19-37', en: 'trolley', uz: 'savdo aravachasi' },
      { id: '19-38', en: 'high street names', uz: 'mashhur do‘konlar' },
      { id: '19-39', en: 'second-hand', uz: 'ikkinchi qo‘l, ishlatilgan' },
      { id: '19-40', en: 'fake', uz: 'soxta (qalbaki)' },
      { id: '19-41', en: 'genuine', uz: 'asl (haqiqiy)' },
      { id: '19-42', en: 'to shop till you drop', uz: 'charchaguncha xarid qilmoq' }
    ]
  },
  {
    id: 'unit-20',
    title: 'Unit 20: Music',
    icon: '🎵',
    words: [
      { id: '20-1', en: 'music genre', uz: 'musiqa janri' },
      { id: '20-2', en: 'blues', uz: 'blus (g‘amgin turdagi qo‘shiq)' },
      { id: '20-3', en: 'background music', uz: 'orqa fondagi musiqa' },
      { id: '20-4', en: 'conductor', uz: 'dirijyor' },
      { id: '20-5', en: 'choir', uz: 'xor' },
      { id: '20-6', en: 'band', uz: 'musiqa guruhi' },
      { id: '20-7', en: 'composer', uz: 'bastakor' },
      { id: '20-8', en: 'venue', uz: 'joy (yig‘ilish, musobaqa, konsert o‘tkaziladigan)' },
      { id: '20-9', en: 'headphones / earphones', uz: 'quloqchinlar' },
      { id: '20-10', en: 'speaker', uz: 'karnay, kalonka' },
      { id: '20-11', en: 'a catchy tune', uz: 'esda qoladigan ohang' },
      { id: '20-12', en: 'rhythm', uz: 'ritm' },
      { id: '20-13', en: 'to have a great voice', uz: 'yaxshi qo‘shiq kuylamoq' },
      { id: '20-14', en: 'chorus', uz: 'naqorat' },
      { id: '20-15', en: 'upbeat', uz: 'quvnoq, sho‘x (musiqa, qo‘shiq)' },
      { id: '20-16', en: 'nursery rhyme', uz: 'bolalar she’ri' },
      { id: '20-17', en: 'lullaby', uz: 'alla' },
      { id: '20-18', en: 'sing to sleep', uz: 'allalamoq' },
      { id: '20-19', en: 'to cheer up', uz: 'kayfiyatni ko‘tarmoq' },
      { id: '20-20', en: 'frontman', uz: 'asosiy qo‘shiqchi' },
      { id: '20-21', en: 'huge following', uz: 'ko‘p sonli muxlislar' },
      { id: '20-22', en: 'to sing along to', uz: 'qo‘shiqqa jo‘r bo‘lmoq' },
      { id: '20-23', en: 'music-lover', uz: 'musiqa shaydosi' },
      { id: '20-24', en: 'applause', uz: 'qarsak' },
      { id: '20-25', en: 'to improvise', uz: 'improvizatsiya qilmoq' },
      { id: '20-26', en: 'earworm', uz: 'quloqda qolib ketgan qo‘shiq' },
      { id: '20-27', en: 'hum', uz: 'hirgoyi qilmoq' },
      { id: '20-28', en: 'ringtone', uz: 'gudok musiqa' },
      { id: '20-29', en: 'a massive hit', uz: 'katta hit (qo‘shiq)' },
      { id: '20-30', en: 'fan base', uz: 'muxlislar bazasi' }
    ]
  },
  {
    id: 'unit-21',
    title: 'Unit 21: Crime',
    icon: '⚖️',
    words: [
      { id: '21-1', en: 'Imprison', uz: 'qamoqqa olmoq' },
      { id: '21-2', en: 'Petty', uz: 'kichik (jinoyat)' },
      { id: '21-3', en: 'Consequence', uz: 'oqibat, natija' },
      { id: '21-4', en: 'Offence', uz: 'jinoyat' },
      { id: '21-5', en: 'Commit a crime', uz: 'jinoyat sodir etmoq' },
      { id: '21-6', en: 'Deter', uz: 'oldini olmoq' },
      { id: '21-7', en: 'Prevent', uz: 'to‘xtatmoq' },
      { id: '21-8', en: 'Enforce', uz: 'qonunga amal qilinishini nazorat qilmoq' },
      { id: '21-9', en: 'Harsh', uz: 'juda qattiq (jazo)' },
      { id: '21-10', en: 'Vandalism', uz: 'shaxsiy mulkka ziyon yetkazish' },
      { id: '21-11', en: 'Bystander', uz: 'guvoh' },
      { id: '21-12', en: 'Wrongdoing', uz: 'noqonuniy xatti-harakat' },
      { id: '21-13', en: 'Lenient', uz: 'yumshoq (jazo)' },
      { id: '21-14', en: 'Sue', uz: 'sudga bermoq' },
      { id: '21-15', en: 'Take someone to the court', uz: 'birovni sudga bermoq' },
      { id: '21-16', en: 'Weapon', uz: 'qurol' },
      { id: '21-17', en: 'Prohibit', uz: 'taqiqlamoq (qonun bilan)' },
      { id: '21-18', en: 'Legalise', uz: 'qonuniylashtirmoq' },
      { id: '21-19', en: 'Abduction', uz: 'odam o‘g‘irlash' },
      { id: '21-20', en: 'Assault', uz: 'hujum' },
      { id: '21-21', en: 'Human trafficking', uz: 'odam savdosi' },
      { id: '21-22', en: 'Smuggling', uz: 'kontrabanda' },
      { id: '21-23', en: 'Pickpocketing', uz: 'kissavurlik' },
      { id: '21-24', en: 'Running a red light', uz: 'qizil chiroqda o‘tib ketish' },
      { id: '21-25', en: 'The death penalty', uz: 'o‘lim jazosi' },
      { id: '21-26', en: 'House arrest', uz: 'uy qamog‘i' },
      { id: '21-27', en: 'Prosecutor', uz: 'qoralovchi' },
      { id: '21-28', en: 'Arson', uz: 'ataylab o‘t qo‘yish' },
      { id: '21-29', en: 'Organized crime', uz: 'uyushgan jinoyatchilik' },
      { id: '21-30', en: 'Patricide', uz: 'padarkushlik' },
      { id: '21-31', en: 'Genocide', uz: 'genotsid (ma’lum bir xalq yoki irqni yo‘q qilish)' },
      { id: '21-32', en: 'Drunk driving', uz: 'mast holda mashina haydash' }
    ]
  },
  {
    id: 'unit-22',
    title: 'Unit 22: Advertising',
    icon: '📢',
    words: [
      { id: '22-1', en: 'Advertising agency', uz: 'reklama agentligi' },
      { id: '22-2', en: 'Advertising budget', uz: 'reklama budjeti' },
      { id: '22-3', en: 'Brand awareness', uz: 'brendning tanilganligi' },
      { id: '22-4', en: 'Classified ads', uz: 'gazetada e’lonlar beriladigan qismi' },
      { id: '22-5', en: 'Commercial break', uz: 'reklama tanaffusi' },
      { id: '22-6', en: 'Go viral', uz: 'mashhur bo‘lmoq (ijtimoiy tarmoqlarda)' },
      { id: '22-7', en: 'To launch a product', uz: 'yangi mahsulotni tanishtirmoq' },
      { id: '22-8', en: 'Mass media', uz: 'ommaviy axborot vositalari' },
      { id: '22-9', en: 'To place an advert', uz: 'reklama joylashtirmoq' },
      { id: '22-10', en: 'Prime time', uz: 'televizor eng ko‘p ko‘riladigan vaqt' },
      { id: '22-11', en: 'Billboards', uz: 'reklama bannerlari' },
      { id: '22-12', en: 'Tantalizing', uz: 'o‘ziga jalb qiluvchi, havasni keltiradigan' },
      { id: '22-13', en: 'Live up to its hype', uz: 'shov-shuvlarga arzimoq' },
      { id: '22-14', en: 'Grating', uz: 'odamning asabiga tegadigan' },
      { id: '22-15', en: 'Potential customers', uz: 'potensial mijozlar' },
      { id: '22-16', en: 'Pop-ups', uz: 'to‘satdan ekranda paydo bo‘ladigan reklamalar' },
      { id: '22-17', en: 'Impressionable', uz: 'oson ta’sirlanadigan' },
      { id: '22-18', en: 'Flyer', uz: 'tarqatma e’lon' },
      { id: '22-19', en: 'Buying power', uz: 'xarid qobiliyati' },
      { id: '22-20', en: 'Bombard (with)', uz: 'yopirilmoq (reklamalar bilan)' }
    ]
  },
  {
    id: 'unit-23',
    title: 'Unit 23: Clothes & Fashion',
    icon: '👗',
    words: [
      { id: '23-1', en: 'A slave to fashion', uz: 'modaga qul' },
      { id: '23-2', en: 'Must-have', uz: 'bo‘lishi shart bo‘lgan, zaruriy' },
      { id: '23-3', en: 'Old fashioned', uz: 'urfdan qolgan' },
      { id: '23-4', en: 'Casual clothes', uz: 'norasmiy kiyimlar' },
      { id: '23-5', en: 'Getting dressed up', uz: 'yasanib olmoq' },
      { id: '23-6', en: 'To look good in', uz: 'da yaxshi ko‘rinmoq (kiyimda)' },
      { id: '23-7', en: 'Vintage clothes', uz: 'eski kiyimlar' },
      { id: '23-8', en: 'Go out of fashion', uz: 'urfdan qolmoq' },
      { id: '23-9', en: 'To be in fashion', uz: 'urfda bo‘lmoq' },
      { id: '23-10', en: 'Well dressed', uz: 'yaxshi kiyingan' },
      { id: '23-11', en: 'Smart clothes', uz: 'rasmiy kiyimlar' },
      { id: '23-12', en: 'To take pride in one’s appearance', uz: 'ko‘rinishiga e’tibor bermoq' },
      { id: '23-13', en: 'To be on trend', uz: 'urfda bo‘lmoq' },
      { id: '23-14', en: 'Fashionable', uz: 'zamonaviy, urfdagi' },
      { id: '23-15', en: 'Fashion house', uz: 'modalar uyi' },
      { id: '23-16', en: 'Hand-me-downs', uz: 'aka yoki opalardan qolgan kiyimlar' },
      { id: '23-17', en: 'To keep up with the latest fashion', uz: 'so‘nggi urfda kiyinmoq' },
      { id: '23-18', en: 'Suit', uz: 'mos tushmoq, yarashmoq' },
      { id: '23-19', en: 'Attire', uz: 'kiyim' },
      { id: '23-20', en: 'Ripped jeans', uz: 'yamoq jinsilar' },
      { id: '23-21', en: 'Dress code', uz: 'kiyinish qoidasi' },
      { id: '23-22', en: 'Footwear', uz: 'oyoq kiyim' },
      { id: '23-23', en: 'Baggy', uz: 'keng turadigan, holpillab turadigan' },
      { id: '23-24', en: 'Tailor-made', uz: 'tikuvchi tomonidan tikilgan' },
      { id: '23-25', en: 'Long-sleeved / short-sleeved', uz: 'uzun yengli / kalta yengli' },
      { id: '23-26', en: 'Fit like a glove', uz: 'juda mos, yarashmoq' },
      { id: '23-27', en: 'Come in fashion', uz: 'urfga kirmoq' },
      { id: '23-28', en: 'Hoodie', uz: 'kapyushonli kiyim' },
      { id: '23-29', en: 'Timeless clothes', uz: 'hech qachon urfdan qolmaydigan kiyimlar' },
      { id: '23-30', en: 'Have an eye for (fashion)', uz: 'modani yaxshi tushunmoq' }
    ]
  },
  {
    id: 'unit-24',
    title: 'Unit 24: Business & Work',
    icon: '💼',
    words: [
      { id: '24-1', en: 'To be called for an interview', uz: 'suhbatga chaqirilmoq (ish uchun)' },
      { id: '24-2', en: 'A dead-end job', uz: 'istiqboli yo‘q ish (o‘sish imkoni yo‘q)' },
      { id: '24-3', en: 'A good team player', uz: 'jamoa bo‘lib yaxshi ishlovchi odam' },
      { id: '24-4', en: 'Full-time job', uz: 'to‘liq stavkali ish' },
      { id: '24-5', en: 'Part-time job', uz: 'yarim stavkali ish' },
      { id: '24-6', en: 'A high-powered job', uz: 'yuqori martabali ish' },
      { id: '24-7', en: 'Job satisfaction', uz: 'o‘z ishidan qoniqish' },
      { id: '24-8', en: 'Manual work', uz: 'jismoniy mehnat talab qiladigan ish' },
      { id: '24-9', en: 'Maternity leave', uz: 'dekret' },
      { id: '24-10', en: 'To meet a deadline', uz: 'topshiriqni o‘z vaqtida yakunlamoq' },
      { id: '24-11', en: 'Perks of the job', uz: 'ish imtiyozlari' },
      { id: '24-12', en: 'To run your own business', uz: 'o‘z biznesini yuritmoq' },
      { id: '24-13', en: 'Sick leave', uz: 'kasallik tufayli olingan mehnat ta’tili' },
      { id: '24-14', en: 'To be stuck in a rut', uz: 'ilojisiz zerikarli ishda ishlamoq' },
      { id: '24-15', en: 'To take early retirement', uz: 'erta nafaqaga chiqmoq' },
      { id: '24-16', en: 'Temporary work', uz: 'vaqtinchalik ish' },
      { id: '24-17', en: 'To be well paid', uz: 'yaxshi oylik to‘lanadigan' },
      { id: '24-18', en: 'Working conditions', uz: 'ish sharoitlari' },
      { id: '24-19', en: 'To draw up a business plan', uz: 'biznes reja tuzmoq' },
      { id: '24-20', en: 'To earn a living', uz: 'pul topmoq' },
      { id: '24-21', en: 'To go bust', uz: 'bankrot bo‘lmoq, yopilmoq' },
      { id: '24-22', en: 'To go into business with', uz: 'bilan biznesga kirmoq (kim bilandir)' },
      { id: '24-23', en: 'To make a profit', uz: 'foyda olmoq' },
      { id: '24-24', en: 'To raise a company profile', uz: 'kompaniya nomini oshirmoq' },
      { id: '24-25', en: 'To set up a business', uz: 'biznes boshlamoq' },
      { id: '24-26', en: 'Stiff competition', uz: 'kuchli raqobat' },
      { id: '24-27', en: 'To take on employees', uz: 'odamlarni ishga olmoq' },
      { id: '24-28', en: 'To take out a loan', uz: 'qarz olmoq' },
      { id: '24-29', en: 'Nine-to-five job', uz: 'haftasiga 5 kun 9 soatdan ishlanadigan ish (odatiy ish, ofis ishi)' },
      { id: '24-30', en: 'Heavy workload', uz: 'og‘ir ish yoki topshiriq' }
    ]
  }
];

export const TENSE_DATA: Tense[] = [
  { 
    id: 'present-simple', 
    title: 'Present Simple', 
    formula: '(+) S + V1 (-s/es)\n(-) S + do/does + not + V1\n(?) Do/Does + S + V1?', 
    example: 'I work every day.\nHe works at a bank.\nI don\'t play football.\nDoes she like tea?', 
    description: '### 📌 1. Present Simple nima?\nPresent Simple — bu oddiy hozirgi zamon.\n\n### 👉 Qachon ishlatiladi?\n*   **Doimiy ishlar** (habit)\n*   **Faktlar** (haqiqatlar)\n*   **Jadval, reja**\n\n### 📌 2. Eng oson formulasi\n**✅ Oddiy gap:**\n`Subject + Verb (V1)`\n\n| Subject | Verb |\n| :--- | :--- |\n| I / You / We / They | work |\n| He / She / It | works |\n\n### 📌 3. MUHIM QOIDA (eng asosiy joy ⚠️)\n👉 Agar **He / She / It** bo‘lsa → verbga **-s / -es** qo‘shiladi\n\n**Misollar:**\n*   I work → Men ishlayman\n*   He works → U ishlaydi\n*   She likes tea → U choyni yaxshi ko‘radi\n*   It rains → Yomg‘ir yog‘adi\n\n### 📌 4. Qachon -es qo‘shiladi?\nAgar fe’l quyidagilar bilan tugasa:\n👉 **-sh, -ch, -ss, -x, -o**\n\n**Misol:**\ngo → goes, watch → watches, wash → washes\n\n### 📌 5. Inkor gap (Negative)\n👉 **Formula:**\n`Subject + do/does + not + V1`\n\n| Subject | Yordamchi |\n| :--- | :--- |\n| I / You / We / They | do not (don’t) |\n| He / She / It | does not (doesn’t) |\n\n**Misollar:**\n*   I do not work → Men ishlamayman\n*   He does not work → U ishlamaydi\n\n⚠️ **Eslatma:**\n👉 **does** bo‘lsa, fe’lga **s** qo‘shilmaydi!\n❌ He doesn’t works\n✅ He doesn’t work\n\n### 📌 6. Savol gap (Question)\n👉 **Formula:**\n`Do/Does + Subject + V1 ?`\n\n**Misollar:**\n*   Do you work? → Sen ishlaysanmi?\n*   Does he work? → U ishlaydimi?\n\n### 📌 7. Qachon ishlatamiz?\n1.  **Doimiy ishlar**: I wake up at 7, I play football\n2.  **Faktlar**: The sun rises in the east, Water boils at 100°C\n3.  **Jadval**: The train leaves at 9\n\n### 📌 8. Signal so‘zlar\nBu so‘zlarni ko‘rsang — Present Simple bo‘ladi:\n👉 **always, usually, often, sometimes, never**\n\n### 📌 9. Eng muhim xatolar 🚫\n❌ He go to school\n✅ He goes to school\n❌ He doesn’t goes\n✅ He doesn’t go\n\n🔥 **LIFEHACK**\nHe/She/It = **+S**\nDoes = **S yo‘q**'
  },
  { 
    id: 'present-continuous', 
    title: 'Present Continuous', 
    formula: 'Subject + am / is / are + V-ing', 
    example: 'I am studying.\nHe is working.\nThey are playing football.', 
    description: '### 📌 1. Present Continuous nima?\n👉 Hozir ayni paytda bo‘layotgan ish uchun ishlatiladi.\n📍 Oddiy qilib: hozir nima qilayapsan? — shu zamon!\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + am / is / are + V-ing`\n\n| Subject | Yordamchi |\n| :--- | :--- |\n| I | am |\n| He / She / It | is |\n| You / We / They | are |\n\n### 📌 3. Misollar:\n*   I am studying → Men hozir o‘qiyapman\n*   He is working → U hozir ishlayapti\n*   They are playing → Ular o‘ynayapti\n\n### 📌 4. -ing qo‘shish qodalari\n1.  **Oddiy**: work → working\n2.  **“e” tushadi**: make → making\n3.  **Oxiri 1 unli + 1 undosh** → 2 marta yoziladi: run → running\n\n### 📌 5. Inkor gap (Negative)\n`Subject + am/is/are + not + V-ing`\n\n**Misollar:**\n*   I am not studying → Men o‘qimayapman\n*   He is not working → U ishlamayapti\n\n### 📌 6. Savol gap (Question)\n`Am / Is / Are + Subject + V-ing?`\n\n**Misollar:**\n*   Are you studying? → Sen o‘qiyapsanmi?\n*   Is he working? → U ishlayaptimi?\n\n### 📌 7. Qachon ishlatiladi?\n1.  **Hozir ayni paytda**: I am eating\n2.  **Vaqtincha ishlar**: I am learning English these days\n3.  **Hozirgi o‘zgarishlar**: The weather is getting colder\n\n### 📌 8. Signal so‘zlar\n👉 **now, at the moment, right now, currently**\n\n### 📌 9. Eng muhim xatolar 🚫\n❌ I am study\n✅ I am studying\n❌ She playing\n✅ She is playing\n\n🔥 **SUPER LIFEHACK**\nam / is / are + V-ing = Hozir bo\'layotgan ish!' 
  },
  { 
    id: 'present-perfect', 
    title: 'Present Perfect', 
    formula: 'Subject + have / has + V3', 
    example: 'I have finished my work.\nHe has gone to school.\nThey have seen this film.', 
    description: '### 📌 1. Present Perfect nima?\n👉 O‘tmishda bo‘lgan, lekin hozir bilan bog‘liq ishlar uchun.\n📍 Oddiy qilib: **natija hozir muhim!**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + have / has + V3`\n\n| Subject | Yordamchi |\n| :--- | :--- |\n| I / You / We / They | have |\n| He / She / It | has |\n\n### 📌 3. V3 nima?\n👉 Fe’lning 3-shakli (Past Participle)\n*   go → **gone**\n*   eat → **eaten**\n*   do → **done**\n\n### 📌 4. Misollar:\n*   I have finished my work → Men ishni tugatdim (natija bor)\n*   He has gone to school → U maktabga ketgan (hali u yerda)\n\n### 📌 5. Inkor gap (Negative)\n`Subject + have/has + not + V3`\n\n### 📌 6. Savol gap (Question)\n`Have / Has + Subject + V3?`\n\n### 📌 7. Qachon ishlatiladi? 🔥\n1.  **Natija muhim**: I have lost my phone (Telefonim hozir yo\'q)\n2.  **Tajriba**: I have visited Tashkent (Borganman)\n3.  **Davom etayotgan ish**: I have lived here for 5 years\n\n### 📌 8. Signal so‘zlar\n👉 **already, just, yet, ever, never, for, since**\n\n### 📌 9. Past Simple bilan farqi ⚠️\n*   **Present Perfect**: Qachonligi muhim emas\n*   **Past Simple**: Bo\'lgan vaqti aniq\n\n### 📌 10. Eng muhim xatolar 🚫\n❌ I have went\n✅ I have gone\n❌ He have done\n✅ He has done\n\n🔥 **SUPER LIFEHACK**\nNatija hozir muhim bo\'lsa — Present Perfect!' 
  },
  { 
    id: 'present-perfect-continuous', 
    title: 'Present Perfect Continuous', 
    formula: 'Subject + have/has + been + V-ing', 
    example: 'I have been studying for 2 hours.\nHe has been working since morning.', 
    description: '### 📌 1. Present Perfect Continuous nima?\n👉 O‘tmishda boshlangan va hozirgacha davom etayotgan ish uchun.\n📍 Oddiy qilib: **qancha vaqt davom etayapti?**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + have/has + been + V-ing`\n\n### 📌 3. Misollar:\n*   I have been studying → Men o‘qib kelayapman\n*   He has been working → U ishlab kelayapti\n\n### 📌 4. Qachon ishlatiladi? 🔥\n1.  **Davomiylik**: I have been studying for 2 hours\n2.  **Natija ko‘rinib turibdi**: She is tired because she has been working\n\n### 📌 5. Signal so‘zlar\n👉 **for (qancha vaqt), since (qachondan beri)**\n\n### 📌 6. Inkor va Savol\n*   **Inkor**: Subject + have/has not been + V-ing\n*   **Savol**: Have/Has + Subject + been + V-ing?\n\n### 📌 7. Present Perfect bilan farqi\n*   **Perfect**: Natija\n*   **Perfect Continuous**: Jarayon (davom etyapman)\n\n### 📌 8. Eng muhim xatolar 🚫\n❌ I have been study\n✅ I have been studying\n❌ I am been working\n✅ I have been working\n\n🔥 **SUPER LIFEHACK**\nfor / since bo\'lsa 90% holatda shu zamon!' 
  },
  { 
    id: 'past-simple', 
    title: 'Past Simple', 
    formula: '(+) S + V2 (-ed / irregular)\n(-) S + did not + V1\n(?) Did + S + V1?', 
    example: 'I worked yesterday.\nHe went to school.\nI didn\'t see him.', 
    description: '### 📌 1. Past Simple nima?\n👉 O‘tgan zamonda bo‘lib tugagan ishlar uchun.\n📍 Oddiy qilib: **kecha nima qilding?**\n\n### 📌 2. Formula (eng muhim ⚠️)\n**✅ Oddiy gap:** `Subject + V2`\n\n### 📌 3. V2 nima?\n1.  **Regular**: work → worked (-ed qo\'shiladi)\n2.  **Irregular**: go → went, eat → ate (yodlash kerak)\n\n### 📌 4. Inkor gap (Negative)\n`Subject + did not + V1`\n⚠️ **Did** bo\'lsa, fe\'lga s yoki ed qo\'shilmaydi!\n❌ I didn\'t went\n✅ I didn\'t go\n\n### 📌 5. Savol gap (Question)\n`Did + Subject + V1?`\n\n### 📌 6. Signal so‘zlar\n👉 **yesterday, last week, ago, in 2020**\n\n### 📌 7. Eng muhim xatolar 🚫\n❌ I did not went\n✅ I did not go\n❌ Did you went?\n✅ Did you go?\n\n🔥 **SUPER LIFEHACK**\nPositive → **V2**, Negative/Question → **did + V1**' 
  },
  { 
    id: 'past-continuous', 
    title: 'Past Continuous', 
    formula: 'Subject + was / were + V-ing', 
    example: 'I was studying at 8 pm.\nThey were playing while I was watching TV.', 
    description: '### 📌 1. Past Continuous nima?\n👉 O‘tmishda ma’lum bir vaqtda davom etayotgan ish.\n📍 Oddiy qilib: **kecha soat 8 da nima qilayotgan eding?**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + was / were + V-ing`\n\n| Subject | Yordamchi |\n| :--- | :--- |\n| I / He / She / It | was |\n| You / We / They | were |\n\n### 📌 3. Misollar:\n*   I was studying → Men o\'qiyotgan edim\n*   They were playing → Ular o\'ynayotgan edi\n\n### 📌 4. Inkor va Savol\n*   **Inkor**: Subject + was/were not + V-ing\n*   **Savol**: Was/Were + Subject + V-ing?\n\n### 📌 5. Qachon ishlatiladi? 🔥\n1.  **Aniq vaqt**: I was studying at 8 pm yesterday\n2.  **Boshqa ish bilan birga**: I was studying when he called\n\n### 📌 6. Signal so‘zlar\n👉 **while (paytida), when (qachonki)**\n\n### 📌 7. Eng muhim xatolar 🚫\n❌ I was study\n✅ I was studying\n❌ They was playing\n✅ They were playing' 
  },
  { 
    id: 'past-perfect', 
    title: 'Past Perfect', 
    formula: 'Subject + had + V3', 
    example: 'I had finished my work before he came.\nHe had left when I arrived.', 
    description: '### 📌 1. Past Perfect nima?\n👉 O‘tmishda bir ish boshqa ishdan oldin bo‘lib tugaganini ko‘rsatadi.\n📍 Oddiy qilib: **“o‘sha paytdan ham oldin nima bo‘lgandi?”**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + had + V3` (Hammasiga had)\n\n### 📌 3. Misollar:\n*   I had finished my work → Men ishni tugatgan edim\n*   He had gone to school → U maktabga ketgan edi\n\n### 📌 4. Qachon ishlatiladi? 🔥\n1.  **Ikki o‘tgan ish**: Bir ish oldin, biri keyin bo\'lsa.\n2.  **“when / before / after”** bilan ko\'p keladi.\n\n### 📌 5. Signal so‘zlar\n👉 **before, after, when, already**\n\n### 📌 6. Eng muhim xatolar 🚫\n❌ I had went\n✅ I had gone\n❌ I had finish\n✅ I had finished\n\n🔥 **SUPER LIFEHACK**\nO\'tgan zamondagi ikkita ishdan birinchi bo\'lgani — **Past Perfect**!' 
  },
  { 
    id: 'past-perfect-continuous', 
    title: 'Past Perfect Continuous', 
    formula: 'Subject + had been + V-ing', 
    example: 'I had been studying for 2 hours before the exam started.', 
    description: '### 📌 1. Past Perfect Continuous nima?\n👉 O‘tmishda bir ish boshqa ishdan OLDIN uzoq vaqt davom etib kelganini ko‘rsatadi.\n📍 Oddiy qilib: **qancha vaqt davom etib kelayotgan edi?**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + had been + V-ing`\n\n### 📌 3. Qachon ishlatiladi? 🔥\n1.  **Davomiylik**: I had been studying for 2 hours before the exam\n2.  **Sabab**: She was tired because she had been working\n\n### 📌 4. Signal so‘zlar\n👉 **for, since, before**\n\n### 📌 5. Eng muhim xatolar 🚫\n❌ I had been study\n✅ I had been studying\n❌ I was been studying\n✅ I had been studying' 
  },
  { 
    id: 'future-simple', 
    title: 'Future Simple', 
    formula: 'Subject + will + V1', 
    example: 'I will study tomorrow.\nHe won\'t go to the party.\nWill you help me?', 
    description: '### 📌 1. Future Simple nima?\n👉 Kelajakda bo‘ladigan ishlar uchun.\n📍 Oddiy qilib: **ertaga nima qilasan?**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + will + V1` (Hamma bilan bir xil)\n\n### 📌 3. Inkor va Savol\n*   **Inkor**: Subject + won\'t + V1\n*   **Savol**: Will + Subject + V1?\n\n### 📌 4. Qachon ishlatiladi? 🔥\n1.  **Tez qaror**: I will open the door (Hozir qaror qildim)\n2.  **Bashorat**: It will rain tomorrow\n3.  **Va’da / taklif**: I will help you\n\n### 📌 5. Signal so‘zlar\n👉 **tomorrow, next week, soon, later**\n\n### 📌 6. Going to bilan farqi ⚠️\n*   **Will**: Hozirgi qaror\n*   **Going to**: Rejalashtirilgan ish\n\n🔥 **SUPER LIFEHACK**\nwill + V1 = Kelajakda qilaman!' 
  },
  { 
    id: 'future-continuous', 
    title: 'Future Continuous', 
    formula: 'Subject + will be + V-ing', 
    example: 'I will be studying at this time tomorrow.', 
    description: '### 📌 1. Future Continuous nima?\n👉 Kelajakda ma’lum bir vaqtda davom etayotgan ish.\n📍 Oddiy qilib: **ertaga shu paytda nima qilayotgan bo‘lasan?**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + will be + V-ing`\n\n### 📌 3. Misollar:\n*   I will be studying → Men o‘qiyotgan bo‘laman\n*   He will be working → U ishlayotgan bo‘ladi\n\n### 📌 4. Qachon ishlatiladi? 🔥\n1.  **Aniq vaqt**: I will be studying at 8 pm tomorrow\n2.  **Taxmin**: He will be sleeping now (U uxlayotgandir)\n\n### 📌 5. Signal so‘zlar\n👉 **at this time tomorrow, at 5 pm tomorrow**' 
  },
  { 
    id: 'future-perfect', 
    title: 'Future Perfect', 
    formula: 'Subject + will have + V3', 
    example: 'I will have finished my homework by 9 pm.', 
    description: '### 📌 1. Future Perfect nima?\n👉 Kelajakda ma’lum bir vaqtgacha ish tugagan bo‘ladi.\n📍 Oddiy qilib: **“...gacha tugatgan bo‘laman”**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + will have + V3`\n\n### 📌 3. Qachon ishlatiladi? 🔥\n1.  **Deadline**: I will have finished my homework by 9 pm\n2.  **Kelajak natijasi**: She will have arrived by tomorrow\n\n### 📌 4. Signal so‘zlar\n👉 **by (gacha) — eng muhimi!**, by next week, by 2026\n\n### 📌 5. Eng muhim xatolar 🚫\n❌ I will have went\n✅ I will have gone\n❌ I will have finish\n✅ I will have finished' 
  },
  { 
    id: 'future-perfect-continuous', 
    title: 'Future Perfect Continuous', 
    formula: 'Subject + will have been + V-ing', 
    example: 'I will have been studying for 3 hours by 9 pm.', 
    description: '### 📌 1. Future Perfect Continuous nima?\n👉 Kelajakda ma’lum bir vaqtgacha ish qancha vaqt davom etgan bo‘ladi.\n📍 Oddiy qilib: **“…dan beri … qilib kelayotgan bo‘laman”**\n\n### 📌 2. Formula (eng muhim ⚠️)\n`Subject + will have been + V-ing`\n\n### 📌 3. Qachon ishlatiladi? 🔥\n1.  **Davomiylik + Kelajak**: I will have been studying for 3 hours by 9 pm\n\n### 📌 4. Signal so‘zlar\n👉 **for, since, by**' 
  }
];
