
import { Unit, Word } from './types';

export const CUSTOM_VOCAB: Record<string, Word[]> = {
  SHORT: [
    { id: 's-1', en: 'the', uz: 'aniq artikl' },
    { id: 's-2', en: 'a / an', uz: 'noaniq artikl, bir, bitta' },
    { id: 's-3', en: 'to', uz: "yo'nalish kelishigi (ga), maqsad (uchun)" },
    { id: 's-4', en: 'of', uz: 'qaratqich kelishigi (ning)' },
    { id: 's-5', en: 'in', uz: "o'rin-payt kelishigi (da), ichida" },
    { id: 's-6', en: 'on', uz: 'ustida, sirtida' },
    { id: 's-7', en: 'at', uz: 'aniq bir joyda (da)' },
    { id: 's-8', en: 'for', uz: 'uchun' },
    { id: 's-9', en: 'with', uz: 'bilan' },
    { id: 's-10', en: 'from', uz: 'dan' },
    { id: 's-11', en: 'is', uz: "dir, bo'lmoq (hozirgi zamon)" },
    { id: 's-12', en: 'are', uz: "dir, bo'lmoq (hozirgi zamon)" },
    { id: 's-13', en: 'was', uz: "edi, bo'lgan (o'tgan zamon)" },
    { id: 's-14', en: 'were', uz: "edi, bo'lgan (o'tgan zamon)" },
    { id: 's-15', en: 'be', uz: "bo'lmoq, mavjud bo'lmoq" },
    { id: 's-16', en: 'have', uz: "ega bo'lmoq, bor bo'lmoq" },
    { id: 's-17', en: 'has', uz: "ega bo'lmoq, bor bo'lmoq (u)" },
    { id: 's-18', en: 'do', uz: 'qilmoq, bajarmoq' },
    { id: 's-19', en: 'go', uz: 'bormoq' },
    { id: 's-20', en: 'get', uz: 'olmoq' },
    { id: 's-21', en: 'see', uz: "ko'rmoq" },
    { id: 's-22', en: 'say', uz: 'aytmoq' },
    { id: 's-23', en: 'make', uz: 'yasamoq, yaratmoq, qilmoq' },
    { id: 's-24', en: 'I', uz: 'men' },
    { id: 's-25', en: 'you', uz: 'sen / siz' },
    { id: 's-26', en: 'he', uz: 'u (erkak jinsiga nisbatan)' },
    { id: 's-27', en: 'she', uz: 'u (ayol jinsiga nisbatan)' },
    { id: 's-28', en: 'it', uz: 'u (narsa va hayvonlarga nisbatan)' },
    { id: 's-29', en: 'we', uz: 'biz' },
    { id: 's-30', en: 'they', uz: 'ular' },
    { id: 's-31', en: 'me', uz: 'meni / menga' },
    { id: 's-32', en: 'him', uz: 'uni, unga (erkak jinsiga nisbatan)' },
    { id: 's-33', en: 'her', uz: 'uni, unga (ayol jinsiga nisbatan)' },
    { id: 's-34', en: 'my', uz: 'mening' },
    { id: 's-35', en: 'your', uz: 'sening / sizning' },
    { id: 's-36', en: 'his', uz: 'uning (erkak jinsiga nisbatan)' },
    { id: 's-37', en: 'and', uz: 'va' },
    { id: 's-38', en: 'or', uz: 'yoki' },
    { id: 's-39', en: 'but', uz: 'lekin' },
    { id: 's-40', en: 'if', uz: 'agar, basharti' },
    { id: 's-41', en: 'so', uz: 'shuning uchun, shunday qilib' },
    { id: 's-42', en: 'not', uz: 'emas' },
    { id: 's-43', en: 'no', uz: "yo'q" },
    { id: 's-44', en: 'yes', uz: 'ha' },
    { id: 's-45', en: 'this', uz: 'bu' },
    { id: 's-46', en: 'that', uz: "u, ana u, o'sha" },
    { id: 's-47', en: 'here', uz: 'bu yerda' },
    { id: 's-48', en: 'there', uz: 'u yerda' },
    { id: 's-49', en: 'what', uz: 'nima' },
    { id: 's-50', en: 'who', uz: 'kim' },
    { id: 's-51', en: 'when', uz: 'qachon' },
    { id: 's-52', en: 'where', uz: 'qayerda' },
    { id: 's-53', en: 'can', uz: 'qila olmoq, imkoniyati bo\'lmoq' },
    { id: 's-54', en: 'will', uz: 'qilaman (kelasi zamon)' }
  ],
  B_PLUS: [
    // TOPIC VOCABULARY (UNIT 3)
    { id: 'b-1', en: 'beat', uz: "yengmoq, mag'lub etmoq" },
    { id: 'b-2', en: 'board game', uz: "stoli o'yini, doska o'yini" },
    { id: 'b-3', en: 'captain', uz: 'sardor (kapitan)' },
    { id: 'b-4', en: 'challenge', uz: 'chaqiruv (musobaqaga)' },
    { id: 'b-5', en: 'champion', uz: 'champion' },
    { id: 'b-6', en: 'cheat', uz: "g'irromlik qilmoq, aldash" },
    { id: 'b-7', en: 'classical music', uz: 'mumtoz musiqa' },
    { id: 'b-8', en: 'club', uz: 'klub' },
    { id: 'b-9', en: 'coach', uz: 'murabbiy' },
    { id: 'b-10', en: 'competition', uz: 'musobaqa' },
    { id: 'b-11', en: 'concert', uz: 'konsert' },
    { id: 'b-12', en: 'defeat', uz: "mag'lubiyat, mag'lub etmoq" },
    { id: 'b-13', en: 'entertaining', uz: 'ko\'ngilochar' },
    { id: 'b-14', en: 'folk music', uz: 'folklor musiqa' },
    { id: 'b-15', en: 'group', uz: 'guruh' },
    { id: 'b-16', en: 'gym', uz: 'sport zali, gimnastika zali' },
    { id: 'b-17', en: 'have fun', uz: 'xursandchilik qilmoq' },
    { id: 'b-18', en: 'interest', uz: 'qiziqtirmoq' },
    { id: 'b-19', en: 'member', uz: "a'zo" },
    { id: 'b-20', en: 'opponent', uz: 'raqib, qarshi tomon' },
    { id: 'b-21', en: 'organize', uz: 'tashkillashtirmoq, uyushtirmoq' },
    { id: 'b-22', en: 'pleasure', uz: 'rohat' },
    { id: 'b-23', en: 'referee', uz: 'hakam' },
    { id: 'b-24', en: 'rhythm', uz: 'marom / maqom' },
    { id: 'b-25', en: 'risk', uz: 'tavakkal qilmoq, xavf-xatarga qo\'yish' },
    { id: 'b-26', en: 'score', uz: 'ochko (gol kiritmoq)' },
    { id: 'b-27', en: 'support', uz: "qo'llab-quvvatlash" },
    { id: 'b-28', en: 'team', uz: 'jamoa' },
    { id: 'b-29', en: 'train', uz: "shug'ullanmoq, mashq qilmoq" },
    { id: 'b-30', en: 'video game', uz: "kompyuter o'yini" },
    
    // PHRASAL VERBS
    { id: 'b-31', en: 'Carry on', uz: 'davom ettirmoq' },
    { id: 'b-32', en: 'Eat out', uz: 'restoranda ovqatlanmoq' },
    { id: 'b-33', en: 'Give up', uz: 'taslim bo\'lmoq, odatni tashlamoq' },
    { id: 'b-34', en: 'Join in', uz: "qo'shilmoq, ishtirok etmoq" },
    { id: 'b-35', en: 'Send off', uz: "o'yindan chetlashtirmoq" },
    { id: 'b-36', en: 'Take up', uz: 'shug\'ullanishni boshlamoq (hobby, sport)' },
    { id: 'b-37', en: 'Turn down', uz: 'rad etmoq, ovozni pasaytirmoq' },
    { id: 'b-38', en: 'Turn up', uz: 'paydo bo\'lmoq, ovozni ko\'tarmoq' },

    // PREPOSITIONAL PHRASES
    { id: 'b-39', en: 'For a long time', uz: 'uzoq vaqt mobaynida' },
    { id: 'b-40', en: 'For fun', uz: 'ermak uchun' },
    { id: 'b-41', en: 'In the middle (of)', uz: "ning o'rtasida" },
    { id: 'b-42', en: 'In time (for)', uz: 'o\'z vaqtida, kechikmasdan' },
    { id: 'b-43', en: 'On CD/DVD/video', uz: 'CD/DVD/videoda' },
    { id: 'b-44', en: 'On stage', uz: 'sahnada' },

    // WORD FORMATION (SELECTED)
    { id: 'b-45', en: 'Athlete', uz: 'atletikachi, sportchi' },
    { id: 'b-46', en: 'Childhood', uz: 'bolalik' },
    { id: 'b-47', en: 'Collection', uz: 'kolleksiya' },
    { id: 'b-48', en: 'Entertainer', uz: "so'z ustasi, qiziqchi, ko'ngilochar shaxs" },
    { id: 'b-49', en: 'Heroic', uz: 'mardlarcha' },
    { id: 'b-50', en: 'Musical', uz: 'musiqiy' },
    { id: 'b-51', en: 'Player', uz: "o'yinchi" },
    { id: 'b-52', en: 'Sailing', uz: 'dengiz safari' },
    { id: 'b-53', en: 'Singing', uz: 'kuylash' },

    // WORD PATTERNS
    { id: 'b-54', en: 'Bored with', uz: 'dan zerikmoq' },
    { id: 'b-55', en: 'Crazy about', uz: "ga juda ham qiziqmoq, jinnisi bo'lmoq" },
    { id: 'b-56', en: 'Good at', uz: 'dan yaxshi' },
    { id: 'b-57', en: 'Interested in', uz: 'ga qiziqmoq' },
    { id: 'b-58', en: 'Keen on', uz: "ga ishqiboz bo'lmoq" },
    { id: 'b-59', en: 'Popular with', uz: 'orasida mashhur, ommabop' },
    { id: 'b-60', en: 'Feel like', uz: 'xohlamoq, istamoq' },
    { id: 'b-61', en: 'Take part in', uz: 'da ishtirok etmoq, qatnashmoq' },

    // UNIT 6 TOPIC VOCABULARY
    { id: 'b-62', en: 'Achieve', uz: 'erishmoq' },
    { id: 'b-63', en: 'Brain', uz: 'miya / aql' },
    { id: 'b-64', en: 'Clever', uz: 'aqlli' },
    { id: 'b-65', en: 'Concentrate', uz: 'diqqatni jamlamoq' }
  ],
  C_PLUS: []
};

export const VOCAB_DATA: Unit[] = [
  {
    id: 'unit-1',
    title: 'Unit 1: Education',
    icon: '🎓',
    words: [
      { id: '1-1', en: 'To educate', uz: "ta'lim bermoq, o'qitmoq" },
      { id: '1-2', en: 'Compulsory education', uz: "majburiy ta'lim" },
      { id: '1-3', en: 'Preschool education', uz: "maktabgacha ta'lim" },
      { id: '1-4', en: 'Higher education (tertiary)', uz: "oliy ta'lim" },
      { id: '1-5', en: 'Qualification', uz: 'malaka, diplom yoki sertifikat' },
      { id: '1-6', en: "Bachelor's degree", uz: 'bakalavr darajasi' },
      { id: '1-7', en: "Master's degree", uz: 'magistratura' },
      { id: '1-8', en: 'Doctorate (PhD)', uz: 'doktorantura' },
      { id: '1-9', en: 'Headteacher/principal', uz: 'maktab direktori' },
      { id: '1-10', en: 'Tutor', uz: 'repetitor' },
      { id: '1-11', en: 'Mature student', uz: 'yoshi katta talaba' },
      { id: '1-12', en: 'A graduate', uz: 'bitiruvchi' },
      { id: '1-13', en: 'Curriculum', uz: "o'quv dasturi, dars jadvali" },
      { id: '1-14', en: 'Humanities', uz: 'gumanitar fanlar' },
      { id: '1-15', en: 'To play truant', uz: 'besabab dars qoldirmoq' },
      { id: '1-16', en: 'To skip classes', uz: 'darslardan qochmoq' },
      { id: '1-17', en: 'Bookworm', uz: "kitob o'qishni yoqtiruvchi inson" },
      { id: '1-18', en: 'Rote learning', uz: "ko'r-ko'rona yodlamoq" },
      { id: '1-19', en: 'Literacy rate', uz: 'savodxonlik darajasi' },
      { id: '1-20', en: 'Literate (illiterate)', uz: 'savodli (savodsiz)' },
      { id: '1-21', en: 'Extra-curricular activities', uz: "qo'shimcha mashg'ulotlar" },
      { id: '1-22', en: 'Discipline', uz: 'intizom, tartib-qoida' },
      { id: '1-23', en: 'Halls of residence / dormitory', uz: 'talabalar turar joyi' },
      { id: '1-24', en: 'Assignment', uz: 'vazifa, uyga berilgan topshiriq' },
      { id: '1-25', en: 'Distance learning', uz: "masofaviy ta'lim" },
      { id: '1-26', en: 'To sit (take) an exam', uz: 'imtihon topshirmoq' },
      { id: '1-27', en: 'Tuition fee', uz: "kontrakt to'lovi" },
      { id: '1-28', en: 'A student loan', uz: 'talim krediti' },
      { id: '1-29', en: 'Internship', uz: 'amaliyot, tajriba orttirish' },
      { id: '1-30', en: 'To work your way through university', uz: "ham o'qib ham ishlamoq" },
      { id: '1-31', en: 'To fall behind with your studies', uz: "o'qishda orqada qolmoq" },
      { id: '1-32', en: 'To learn something by heart', uz: 'yodlamoq, yoddan bilmoq' },
      { id: '1-33', en: 'Gap year', uz: "akademik ta'til" },
      { id: '1-34', en: 'To drop out', uz: "o'qishni tashlamoq" },
      { id: '1-35', en: 'Well-educated', uz: "yaxshi ta'lim olgan" },
      { id: '1-36', en: 'To revise/review', uz: 'takrorlamoq, mustahkamlamoq' },
      { id: '1-37', en: 'To pass with flying colours', uz: "imtihondan a'lo baholar bilan o'tmoq" },
      { id: '1-38', en: 'To resit/retake an exam', uz: 'imtihonni qayta topshirmoq' }
    ]
  },
  {
    id: 'unit-2',
    title: 'Unit 2: Hometown & Neighbourhood',
    icon: '🏡',
    words: [
      { id: '2-1', en: 'To be born and raised/bred in', uz: "tug'ilib katta bo'lmoq" },
      { id: '2-2', en: 'To be located/situated in', uz: 'da joylashmoq' },
      { id: '2-3', en: 'In the southern/northern part', uz: 'davlatning janubiy/shimoliy qismida' },
      { id: '2-4', en: 'Coastal city', uz: "dengiz bo'yidagi shahar, qirg'oq shahar" },
      { id: '2-5', en: 'Commercial center', uz: 'tijoriy markaz' },
      { id: '2-6', en: 'Suburbs/outskirts', uz: 'shahar tashqarisi' },
      { id: '2-7', en: 'Residential area', uz: 'turar joy hududi, aholi yashash joyi' },
      { id: '2-8', en: 'City center/inner city', uz: 'shahar markazi' },
      { id: '2-9', en: 'To be famous for/renown for', uz: 'bilan mashhur' },
      { id: '2-10', en: 'Good atmosphere', uz: 'yaxshi atmosfera, yoqimli muhit' },
      { id: '2-11', en: 'Colourful/vibrant city', uz: 'rangdor/ zavqli shahar' },
      { id: '2-12', en: 'Well-developed', uz: 'yaxshi rivojlangan, taraqqiy etgan' },
      { id: '2-13', en: 'Good infrastructure', uz: 'yaxshi infrastruktura' },
      { id: '2-14', en: 'Good facilities', uz: 'yaxshi qulayliklar, sharoitlar' },
      { id: '2-15', en: 'Lively markets/bars/restaurants', uz: "jo'shqin bozorlar/barlar/restoranlar" },
      { id: '2-16', en: 'Great nightlife', uz: 'ajoyib tungi hayot' },
      { id: '2-17', en: 'Friendly neighbours', uz: "do'stona qo'shnilar" },
      { id: '2-18', en: 'Traffic congestion', uz: 'mashinalar tirbandligi' },
      { id: '2-19', en: 'Air pollution', uz: 'havo ifloslanishi' },
      { id: '2-20', en: 'To be densely populated/overcrowded', uz: 'aholi zich joylashgan' },
      { id: '2-21', en: 'Touristic', uz: "turistik, sayyohlar uchun mo'ljallangan" },
      { id: '2-22', en: 'Bustling', uz: "gavjum, jo'shqin" },
      { id: '2-23', en: 'Hectic', uz: 'juda band' },
      { id: '2-24', en: 'Contemporary', uz: 'zamonaviy, hozirgi zamon' },
      { id: '2-25', en: 'Sprawling', uz: "keng hududga cho'zilgan" },
      { id: '2-26', en: 'Orchard', uz: 'mevazor' },
      { id: '2-27', en: 'Picturesque', uz: 'chiroyli, manzarali (joy)' },
      { id: '2-28', en: 'High-rise', uz: "ko'p qavatli bino, osmono'par" },
      { id: '2-29', en: 'Close-knit', uz: 'ahil, bir-biriga yaqin' },
      { id: '2-30', en: 'Upmarket', uz: "yuqori tabaqa insonlar uchun mo'ljallangan" },
      { id: '2-31', en: 'Out-of-town', uz: 'shahar tashqarisidagi' },
      { id: '2-32', en: 'Pop-up shop', uz: "yarmarka, vaqtinchalik do'konlar" },
      { id: '2-33', en: 'Rural', uz: "qishloqqa oid, qishloq hayoti" }
    ]
  },
  {
    id: 'unit-3',
    title: 'Unit 3: Accommodation',
    icon: '🏢',
    words: [
      { id: '3-1', en: 'Property', uz: "mulk, ko'chmas mulk" },
      { id: '3-2', en: 'Single-storey', uz: 'bir qavatli bino' },
      { id: '3-3', en: 'Two-storey', uz: 'ikki qavatli bino' },
      { id: '3-4', en: 'Flat/apartment', uz: 'kvartira, xonadon' },
      { id: '3-5', en: 'Fully-furnished flat / apartment', uz: "to'liq jihozlangan kvartira" },
      { id: '3-6', en: 'Block of flats / tower block', uz: "ko'p qavatli kvartira" },
      { id: '3-7', en: 'Penthouse', uz: 'bino tepasidagi qimmat uy' },
      { id: '3-8', en: 'Mansion', uz: 'hashamatli uy, koshona' },
      { id: '3-9', en: 'Downtown', uz: 'shahar markazi, ishbilarmonlik hududi' },
      { id: '3-10', en: 'Housing estate', uz: 'bir nechta bir xildagi uylar kvartali' },
      { id: '3-11', en: 'To be within walking distance', uz: 'yaqinda joylashgan' },
      { id: '3-12', en: 'Dining room', uz: 'oshxona, ovqatlanish xonasi' },
      { id: '3-13', en: 'Hall / hallway', uz: 'dahliz, koridor' },
      { id: '3-14', en: 'Basement / cellar', uz: "yerto'la, podval" },
      { id: '3-15', en: 'Attic / loft', uz: 'boloxona, chordoq' },
      { id: '3-16', en: 'Balcony', uz: 'balkon' },
      { id: '3-17', en: 'To rent out / let out', uz: 'uyini ijaraga bermoq' },
      { id: '3-18', en: 'Landlord / landlady', uz: 'ijara beruvchi' },
      { id: '3-19', en: 'Tenant', uz: 'ijarada turuvchi odam' },
      { id: '3-20', en: 'Evict', uz: 'uydan haydab chiqarmoq' },
      { id: '3-21', en: 'Estate agent', uz: 'ko\'chmas mulk agenti, makler' },
      { id: '3-22', en: 'Mortgage', uz: 'ipoteka krediti' },
      { id: '3-23', en: 'Mod cons', uz: 'barcha uy jihozlari' },
      { id: '3-24', en: 'Fitted kitchen', uz: "jihozlangan oshxona" },
      { id: '3-25', en: 'Utilities', uz: 'kommunal xizmatlar' },
      { id: '3-26', en: 'Spacious', uz: 'keng, keng maydonli' },
      { id: '3-27', en: 'Cosy', uz: 'shinam, qulay' },
      { id: '3-28', en: 'Lift / Elevator', uz: 'lift' },
      { id: '3-29', en: 'Lawn', uz: 'maysazor, gazon' },
      { id: '3-30', en: 'Terrace / patio', uz: 'ayvon' },
      { id: '3-31', en: 'Fence', uz: "devor, to'siq" },
      { id: '3-32', en: 'To redecorate', uz: 'qayta bezamoq, pardozlamoq' },
      { id: '3-33', en: 'To renovate', uz: 'remont qilmoq, yangilamoq' },
      { id: '3-34', en: 'To do up a property', uz: 'mulkni tamirlamoq, tartibga keltirish' },
      { id: '3-35', en: 'To paper the walls', uz: "devorga gulqog'oz yopishtirmoq, oboylamoq" },
      { id: '3-36', en: 'Dream home', uz: 'orzudagi uy' },
      { id: '3-37', en: 'House-warming party', uz: 'yangi uy bazmi' },
      { id: '3-38', en: 'To move in/out', uz: "ko'chib kirmoq/chiqmoq" },
      { id: '3-39', en: 'Downsize', uz: "kichikroq uyga ko'chmoq" },
      { id: '3-40', en: 'Homesick', uz: 'uyni sog\'inmoq' },
      { id: '3-41', en: "No place like home", uz: "o'z uying o'lan to'shaging" }
    ]
  },
  {
    id: 'unit-4',
    title: 'Unit 4: Hobbies & Interests',
    icon: '🎯',
    words: [
      { id: '4-1', en: 'Spare time', uz: "bo'sh vaqt, dam olish vaqti" },
      { id: '4-2', en: 'Unwind', uz: 'zavqlanmoq, rohat olmoq, dam olmoq' },
      { id: '4-3', en: 'To blow off steam', uz: 'xordiq chiqarmoq, asabni tinchlantirmoq' },
      { id: '4-4', en: "Can't get enough of ...", uz: "dan to'ymaslik, juda ham yoqtirmoq" },
      { id: '4-5', en: 'To take up a hobby', uz: "yangi sevimli mashg'ulotni boshlamoq" },
      { id: '4-6', en: 'To be passionate about', uz: "ga judayam qiziqmoq, ishtiyoqmand bo'lmoq" },
      { id: '4-7', en: 'Pastime', uz: "bo'sh vaqt, sevimli mashg'ulot" },
      { id: '4-8', en: 'Work out', uz: "shug'ullanmoq, jismoniy mashq qilmoq" },
      { id: '4-9', en: 'To relieve stress', uz: "stresni chiqarmoq, ruhiy bosimdan xalos bo'lmoq" },
      { id: '4-10', en: 'Get into nature', uz: "tabiat qo'yniga chiqmoq, tabiatdan bahra olmoq" },
      { id: '4-11', en: 'Hang out', uz: "vaqtni birga o'tkazmoq, aylanish" },
      { id: '4-12', en: 'Catch up with friends', uz: "do'stlar bilan uchrashmoq, yangiliklarni bo'lishmoq" },
      { id: '4-13', en: 'Uplifting', uz: "kayfiyatni ko'taruvchi, ruhlantiruvchi" },
      { id: '4-14', en: 'Adrenaline pumping', uz: 'adrenalin beruvchi, hayajonli' },
      { id: '4-15', en: 'Energizing', uz: 'shijoatli, quvvat beruvchi' },
      { id: '4-16', en: 'Music buff', uz: 'musiqa bilimdoni, musiqa shaydosi' },
      { id: '4-17', en: 'Surf the net', uz: "internetda o'tirmoq, ma'lumot qidirmoq" },
      { id: '4-18', en: 'Movie buff', uz: 'kino ixlosmandi, kino bilimdoni' },
      { id: '4-19', en: 'Fight boredom', uz: "zerikishga qarshi kurashmoq, vaqtni mazmunli o'tkazmoq" },
      { id: '4-20', en: 'Distract', uz: "chalg'itmoq, diqqatni boshqa narsaga qaratmoq" },
      { id: '4-21', en: 'Calming', uz: 'osoyishta, tinchlantiruvchi' },
      { id: '4-22', en: 'Bucket list', uz: "o'lguncha bajarishni xohlagan ishlar ro'yxati" },
      { id: '4-23', en: 'Socialize', uz: "odamlarga qo'shilmoq, muloqot qilmoq" },
      { id: '4-24', en: 'Back then', uz: "avvallari, o'sha paytlarda" },
      { id: '4-25', en: 'Out-of-the-box thinking', uz: 'noodatiy fikrlash, ijodiy yondashuv' },
      { id: '4-26', en: 'Set aside some time', uz: 'vaqt ajratmoq, maxsus vaqt belgilamoq' },
      { id: '4-27', en: 'To have a stroll', uz: 'sayr qilmoq, piyoda yurish' },
      { id: '4-28', en: 'Meet up with friends', uz: "do'stlar bilan uchrashmoq, diydorlashmoq" },
      { id: '4-29', en: 'Let my hair down', uz: "dam olmoq, erkinlikni his qilmoq" },
      { id: '4-30', en: 'Jogging', uz: "yugurish, sog'lomlashtiruvchi yugurish" },
      { id: '4-31', en: 'Beekeeping', uz: 'asalarichilik, asal yetishtirish' }
    ]
  },
  {
    id: 'unit-5',
    title: 'Unit 5: Personality',
    icon: '👤',
    words: [
      { id: '5-1', en: 'Broad-minded', uz: "keng fikrli, bag'rikeng" },
      { id: '5-2', en: 'Easy-going', uz: 'yuragi keng, chiqishuvchan' },
      { id: '5-3', en: 'Extrovert', uz: 'chiqishuvchan' },
      { id: '5-4', en: 'Fair-minded', uz: 'adolatli' },
      { id: '5-5', en: 'Fun-loving', uz: 'xushchaqchaq' },
      { id: '5-6', en: 'Good company', uz: 'yaxshi xamroh, suhbati yoqimli' },
      { id: '5-7', en: 'Sense of humour', uz: "hazilkashlik tuyg'usi, quvnoq" },
      { id: '5-8', en: 'Introvert', uz: 'odamovi' },
      { id: '5-9', en: 'Laid-back', uz: 'yuragi keng' },
      { id: '5-10', en: "Lose one's temper", uz: "tez jahli chiqmoq, o'zini yo'qotmoq" },
      { id: '5-11', en: 'Narrow-minded', uz: 'tor fikrlovchi' },
      { id: '5-12', en: 'Painfully shy', uz: 'judayam uyatchang' },
      { id: '5-13', en: 'Put others first', uz: "boshqalarni o'ylamoq" },
      { id: '5-14', en: 'Quick-tempered', uz: 'qiziqqon, tez jahli chiqadigan' },
      { id: '5-15', en: 'Reserved', uz: 'uyatchang' },
      { id: '5-16', en: 'Self-assured', uz: "o'ziga ishonchi baland, qat'iyatli" },
      { id: '5-17', en: 'Self-centred', uz: "xudbin, faqat o'zini o'ylaydigan" },
      { id: '5-18', en: 'Self-confident', uz: "o'ziga ishonadigan" },
      { id: '5-19', en: 'Self-effacing', uz: 'oddiy, sipo' },
      { id: '5-20', en: 'To take after', uz: "o'xshamoq" },
      { id: '5-21', en: 'Thick-skinned', uz: "terisi qalin, tanqidlarga e'tiborsiz" },
      { id: '5-22', en: 'Trustworthy', uz: 'ishonchli' },
      { id: '5-23', en: 'Two-faced', uz: 'ikkiyuzlamachi, munofiq' },
      { id: '5-24', en: 'Supportive', uz: "g'amxo'r" },
      { id: '5-25', en: 'Cheerful', uz: 'quvnoq' },
      { id: '5-26', en: 'Stingy', uz: "xasis, qizg'anchiq" },
      { id: '5-27', en: 'Overweight', uz: 'semiz, ortiqcha vaznli' },
      { id: '5-28', en: 'Brunette', uz: 'qorasoch' },
      { id: '5-29', en: 'Curly', uz: 'jingalak' },
      { id: '5-30', en: 'Moody', uz: "injiq, kayfiyati tez o'zgaruvchan" },
      { id: '5-31', en: 'Courteous', uz: 'odobli, xushmuomala' },
      { id: '5-32', en: 'Night owl', uz: 'tungi qush, kechasi kech uxlaydigan odam' },
      { id: '5-33', en: 'Early bird', uz: 'erta turuvchi, ertalab barvaqt turadigan odam' },
      { id: '5-34', en: 'Look young for your age', uz: "yoshiga nisbatan yosh ko'rinmoq" },
      { id: '5-35', en: 'Bear a striking resemblance', uz: "ga judayam o'xshamoq" },
      { id: '5-36', en: 'Good-looking', uz: 'chiroyli, kelishgan' },
      { id: '5-37', en: 'Well-built', uz: 'baquvvat, gavdali' },
      { id: '5-38', en: 'Blonde hair', uz: 'sariq soch' },
      { id: '5-39', en: 'Charismatic', uz: 'jozibali' },
      { id: '5-40', en: 'Self-esteem', uz: "o'ziga bo'lgan hurmat" }
    ]
  },
  {
    id: 'unit-6',
    title: 'Unit 6: Family',
    icon: '👪',
    words: [
      { id: '6-1', en: 'Nuclear family', uz: 'kichik oila (faqat ota-ona va farzandlar)' },
      { id: '6-2', en: 'Extended family', uz: "katta oila (qarindosh-urug'lar bilan birga)" },
      { id: '6-3', en: 'Dysfunctional family', uz: "nosog'lom muhitli oila, og'ir oila" },
      { id: '6-4', en: 'Relative', uz: 'qarindosh' },
      { id: '6-5', en: 'Distant relative', uz: 'uzoq qarindosh' },
      { id: '6-6', en: 'Descendant', uz: 'avlod' },
      { id: '6-7', en: 'Ancestor', uz: 'ajdod' },
      { id: '6-8', en: 'Household', uz: "ro'zg'or, uy xo'jaligi" },
      { id: '6-9', en: 'Spouse', uz: "er yoki xotin, turmush o'rtoq" },
      { id: '6-10', en: 'Sibling', uz: 'aka-uka yoki opa-singil' },
      { id: '6-11', en: 'Identical twins', uz: "o'xshash egizaklar" },
      { id: '6-12', en: 'An only child', uz: "yolg'iz farzand" },
      { id: '6-13', en: 'Mother-in-law', uz: 'qaynona' },
      { id: '6-14', en: 'Father-in-law', uz: 'qaynota' },
      { id: '6-15', en: 'Son-in-law', uz: 'kuyov' },
      { id: '6-16', en: 'Daughter-in-law', uz: 'kelin' },
      { id: '6-17', en: 'Brother-in-law', uz: 'pochcha' },
      { id: '6-18', en: 'Sister-in-law', uz: 'yanga' },
      { id: '6-19', en: 'Stepfamily', uz: "o'gay oila" },
      { id: '6-20', en: 'Stepmother', uz: "o'gay ona" },
      { id: '6-21', en: 'To start a family', uz: 'oila qurmoq' },
      { id: '6-22', en: 'To give birth', uz: "bola tug'moq" },
      { id: '6-23', en: 'Offspring', uz: 'farzand' },
      { id: '6-24', en: 'To bring up', uz: 'tarbiyalamoq, voyaga yetkazmoq' },
      { id: '6-25', en: 'Upbringing', uz: 'tarbiya' },
      { id: '6-26', en: 'Breadwinner', uz: 'oila boquvchisi, rizq keltiruvchi' },
      { id: '6-27', en: 'To adopt', uz: 'asrab olmoq' },
      { id: '6-28', en: 'To foster', uz: "qaramog'iga olmoq" },
      { id: '6-29', en: 'Overprotective parents', uz: "o'ta himoya qiladigan ota-onalar" },
      { id: '6-30', en: 'Spoilt child', uz: 'taltaygan, erka farzand' },
      { id: '6-31', en: 'Single parent', uz: "yolg'iz ota/ona" },
      { id: '6-32', en: 'Strict', uz: "qattiqqo'l" },
      { id: '6-33', en: 'Generation gap', uz: 'avlodlar farqi' },
      { id: '6-34', en: 'Hereditary', uz: 'irsiy' },
      { id: '6-35', en: 'Family gathering', uz: "oilaviy yig'in" },
      { id: '6-36', en: 'Close-knit family', uz: 'ahil oila' },
      { id: '6-37', en: 'Widow', uz: 'beva' },
      { id: '6-38', en: 'Get along with', uz: 'yaxshi chiqishmoq' },
      { id: '6-39', en: 'To fall out with', uz: 'urishib qolmoq' },
      { id: '6-40', en: 'Spitting image', uz: "quyib qo'ygan nusxasi" },
      { id: '6-41', en: 'Follow in footsteps', uz: 'izidan yurmoq' },
      { id: '6-42', en: 'Black sheep', uz: 'oilaga isnod keltiruvchi, "qora qo\'y"' }
    ]
  },
  {
    id: 'unit-7',
    title: 'Unit 7: Friends',
    icon: '🤝',
    words: [
      { id: '7-1', en: 'Keep in touch', uz: "aloqada bo'lmoq, xabar olib turmoq" },
      { id: '7-2', en: 'Lose touch', uz: "aloqani uzmoq, uzoqlashib ketmoq" },
      { id: '7-3', en: 'Drift apart', uz: "vaqt o'tishi bilan uzoqlashmoq" },
      { id: '7-4', en: 'Lifelong friend', uz: "bir umrlik do'st" },
      { id: '7-5', en: 'Hit it off', uz: "tezda til topishmoq, darrov do'stlashmoq" },
      { id: '7-6', en: 'Through thick and thin', uz: "yaxshi-yomon kunda, har qanday vaziyatda" },
      { id: '7-7', en: 'Have in common', uz: "o'xshash jihatlarga ega bo'lmoq" },
      { id: '7-8', en: 'Back stabber', uz: "sotqin, ortdan pichoq uruvchi" },
      { id: '7-9', en: 'Vindictive', uz: 'kek saqlovchi' },
      { id: '7-10', en: 'Spiteful', uz: 'ichi qora' },
      { id: '7-11', en: 'Shoulder to cry on', uz: "dardkash, og'ir kunda suyanchiq" },
      { id: '7-12', en: 'Confide in', uz: 'ishonib sirini aytmoq' },
      { id: '7-13', en: 'Sympathetic', uz: 'Hamdard' },
      { id: '7-14', en: 'Respect privacy', uz: 'shaxsiy hayotni hurmat qilmoq' },
      { id: '7-15', en: 'Mentor', uz: "maslahatgo'y" },
      { id: '7-16', en: 'Inspiring', uz: 'ilhombaxsh' },
      { id: '7-17', en: 'Gifted', uz: 'talantli' },
      { id: '7-18', en: 'Daredevil', uz: 'tavakkalchi' },
      { id: '7-19', en: 'Don\'t see eye to eye', uz: 'fikri bir joydan chiqmaslik, tushunmaslik' },
      { id: '7-20', en: 'Fair-weather friend', uz: "faqat yaxshi kunda bor do'st, \"soxta do'st\"" },
      { id: '7-21', en: 'Friends in high places', uz: 'katta tanishlar' },
      { id: '7-22', en: 'Buddy / Pal', uz: "og'ayni" },
      { id: '7-23', en: 'Acquaintance', uz: 'tanish' },
      { id: '7-24', en: 'Circle of friends', uz: "do'stlar davrasi" },
      { id: '7-25', en: 'Bump into', uz: "to'satdan uchrashib qolmoq" },
      { id: '7-26', en: 'Count on', uz: 'ishonmoq' },
      { id: '7-27', en: 'Bestie', uz: "eng yaxshi do'st" },
      { id: '7-28', en: 'Make friends', uz: "do'stlashmoq" },
      { id: '7-29', en: 'Lead separate lives', uz: "boshqa yo'ldan bormoq" },
      { id: '7-30', en: 'Know inside out', uz: "besh qo'lday bilmoq, juda yaxshi bilmoq" }
    ]
  },
  {
    id: 'unit-8',
    title: 'Unit 8: Technology/TV',
    icon: '💻',
    words: [
      { id: '8-1', en: 'Technophile', uz: "texnologiya ishqibozi" },
      { id: '8-2', en: 'Tech-savvy', uz: "texnologiyani yaxshi tushunadigan, zamonaviy" },
      { id: '8-3', en: 'Technophobe', uz: "texnologiyadan qo'rqadigan odam" },
      { id: '8-4', en: 'Cutting-edge', uz: "eng zamonaviy, ilg'or" },
      { id: '8-5', en: 'State-of-the-art', uz: "so'nggi rusumdagi" },
      { id: '8-6', en: 'Advanced', uz: 'rivojlangan' },
      { id: '8-7', en: 'Obsolete', uz: "eskirgan, iste'moldan chiqqan" },
      { id: '8-8', en: 'Computer literate', uz: "kompyuter savodxonligiga ega bo'lmoq" },
      { id: '8-9', en: 'Computer buff', uz: 'kompyuter bilimdoni' },
      { id: '8-10', en: 'Laptop', uz: 'noutbuk' },
      { id: '8-11', en: 'PC', uz: 'shaxshiy kompyuter' },
      { id: '8-12', en: 'Boot up', uz: 'kompyuterni ishga tushirmoq, yoqmoq' },
      { id: '8-13', en: 'Crash', uz: 'tizimning buzilishi, qotib qolishi' },
      { id: '8-14', en: 'Surf the internet', uz: 'internetda qidirmoq' },
      { id: '8-15', en: 'Viral', uz: 'tez tarqaladigan, viral' },
      { id: '8-16', en: 'E-commerce', uz: 'elektron tijorat' },
      { id: '8-17', en: 'Censorship', uz: 'senzura' },
      { id: '8-18', en: 'Internet safety', uz: 'xavfsizligi' },
      { id: '8-19', en: 'Hacker', uz: 'haker' },
      { id: '8-20', en: 'Cyber', uz: 'kiber' },
      { id: '8-21', en: 'Cybersecurity', uz: 'kiber xavfsizlik' },
      { id: '8-22', en: 'Cybercrime', uz: 'kiber jinoyat' },
      { id: '8-23', en: 'User-friendly', uz: 'foydalanishga qulay' },
      { id: '8-24', en: 'AI', uz: 'suniy intellect' },
      { id: '8-25', en: 'Glued to the screen', uz: 'ekranga mixlanib qolmoq' },
      { id: '8-26', en: 'Broadcast', uz: 'efirga uzatmoq' },
      { id: '8-27', en: 'Commercial', uz: 'reklama' },
      { id: '8-28', en: 'Entertainment', uz: "ko'ngil ochish" },
      { id: '8-29', en: 'Current affairs', uz: 'dolzarb mavzular' },
      { id: '8-30', en: 'Propaganda', uz: "targ'ibot" },
      { id: '8-31', en: 'Sedentary lifestyle', uz: "kamharakat, o'tirib ishlaydigan turmush tarzi" },
      { id: '8-32', en: 'Couch potato', uz: "dangasa, televizor qarshisidan ketmaydigan odam" }
    ]
  },
  {
    id: 'unit-9',
    title: 'Unit 9: Books & Films',
    icon: '🎬',
    words: [
      { id: '9-1', en: 'Avid reader', uz: "kitobxon, ashaddiy kitob o'quvchi" },
      { id: '9-2', en: 'Fiction', uz: "badiiy adabiyot (to'qima)" },
      { id: '9-3', en: 'Non-fiction', uz: 'ilmiy-ommabop, hujjatli adabiyot' },
      { id: '9-4', en: 'Paperback', uz: "qog'oz muqovali" },
      { id: '9-5', en: 'Plot', uz: 'syujet, voqealar rivoji' },
      { id: '9-6', en: 'Page-turner', uz: "juda qiziqarli kitob, qo'ldan qo'ygisi kelmaydigan" },
      { id: '9-7', en: 'Very readable', uz: "o'qishga arziydigan" },
      { id: '9-8', en: 'Engrossing', uz: "o'ziga rom etadigan" },
      { id: '9-9', en: 'Thought-provoking', uz: "mulohaza yuritishga undaydigan, o'ylantiruvchi" },
      { id: '9-10', en: 'Protagonist', uz: 'bosh qahramon, ijobiy obraz' },
      { id: '9-11', en: 'Antagonist', uz: 'bosh qahramonga qarshi turuvchi, salbiy obraz' },
      { id: '9-12', en: 'Recommended', uz: 'tavsiya etiladigan' },
      { id: '9-13', en: 'Bestseller', uz: "ko'p sotilgan kitob" },
      { id: '9-14', en: 'Window to the world', uz: "dunyoga oyna, dunyoni tanish vositasi" },
      { id: '9-15', en: 'Escape world', uz: "haqiqatdan chalg'ish, xayollar dunyosiga qochish" },
      { id: '9-16', en: 'Broaden knowledge', uz: 'bilimni kengaytirmoq' },
      { id: '9-17', en: 'Strain on the eye', uz: "ko'zga bosim" },
      { id: '9-18', en: 'Worth seeing', uz: "ko'rishga arziydigan" },
      { id: '9-19', en: 'Dubbed', uz: 'dublyaj qilingan' },
      { id: '9-20', en: 'Blockbuster', uz: "muvaffaqiyat qozongan film" },
      { id: '9-21', en: 'Big budget', uz: 'katta budjetli' },
      { id: '9-22', en: 'Award-winning', uz: 'sovrindor film' },
      { id: '9-23', en: 'Lead role', uz: 'bosh rol' },
      { id: '9-24', en: 'Star', uz: 'yulduz, bosh rolni ijro etish' },
      { id: '9-25', en: 'Believable', uz: 'ishonarli ijro' },
      { id: '9-26', en: 'Favourite scene', uz: 'sevimli sahna' },
      { id: '9-27', en: 'Based on real life', uz: 'hayotga asoslangan' },
      { id: '9-28', en: 'Predictable', uz: "oldindan taxmin qilsa bo'ladigan" },
      { id: '9-29', en: 'Visual effects', uz: 'visual effektlar' },
      { id: '9-30', en: 'Soundtrack', uz: 'saundtrek' },
      { id: '9-31', en: 'Gripping', uz: "o'ziga tortadigan, hayajonli" },
      { id: '9-32', en: 'Nail-biting', uz: "o'ta hayajonli, barmoq tishlatadigan" },
      { id: '9-33', en: 'Remake', uz: 'qaytadan olingan' },
      { id: '9-34', en: 'Sequel', uz: 'keyingi qismi' },
      { id: '9-35', en: 'Extraterrestrial', uz: "o'zga sayyoradagi" },
      { id: '9-36', en: 'Premiere', uz: 'film premyerasi' },
      { id: '9-37', en: 'Not my cup of tea', uz: 'qiziqishimga mos emas' },
      { id: '9-38', en: 'Mimic', uz: "taqlid qilmoq, o'xshatmoq" },
      { id: '9-39', en: 'Time consuming', uz: 'vaqt oladigan' },
      { id: '9-40', en: 'Superficial', uz: 'yuzaki, chuqur bo\'lmagan' },
      { id: '9-41', en: 'Bedtime reading', uz: 'uyqudan oldingi mutolaa' },
      { id: '9-42', en: 'Tear-jerking', uz: "ko'z yosh to'ktiradigan, g'amgin" },
      { id: '9-43', en: 'Cover to cover', uz: 'boshidan oxirigacha, to\'liq o\'qib chiqish' }
    ]
  },
  {
    id: 'unit-10',
    title: 'Unit 10: Food & Cooking',
    icon: '🍲',
    words: [
      { id: '10-1', en: 'Favourite dish', uz: 'sevimli ovqat' },
      { id: '10-2', en: 'Delicacy', uz: 'nozik taom, tansiq taom' },
      { id: '10-3', en: 'Dine out', uz: 'tashqarida ovqatlanmoq' },
      { id: '10-4', en: 'Staple food', uz: 'asosiy oziq-ovqat, kundalik taom' },
      { id: '10-5', en: 'Delicious', uz: 'mazali' },
      { id: '10-6', en: 'Terrific flavour', uz: "ajoyib ta'm" },
      { id: '10-7', en: 'Lovely aroma', uz: "xushbo'y hid" },
      { id: '10-8', en: 'Nutritious', uz: "to'yimli, ozuqaviy moddalarga boy" },
      { id: '10-9', en: 'Healthy diet', uz: "sog'lom parhez, to'g'ri ovqatlanish" },
      { id: '10-10', en: 'Home-cooked food', uz: 'uyda qilingan ovqat' },
      { id: '10-11', en: 'Vegan', uz: 'vegan (hayvon mahsulotlarini mutlaqo yemaydigan)' },
      { id: '10-12', en: 'Fussy eater', uz: 'ovqat tanlaydigan, injiq' },
      { id: '10-13', en: 'Wide menu', uz: 'keng menyu' },
      { id: '10-14', en: 'Beverage', uz: 'ichimlik' },
      { id: '10-15', en: 'Season', uz: "ziravorlar qo'shmoq, ta'm bermoq" },
      { id: '10-16', en: 'Greasy/fatty', uz: "yog'li, moyli" },
      { id: '10-17', en: 'Overeating', uz: "ko'p ovqat yemoq" },
      { id: '10-18', en: 'Food poisoning', uz: 'zaharlanish' },
      { id: '10-19', en: 'Obese', uz: "o'ta semiz, semizlikdan aziyat chekuvchi" },
      { id: '10-20', en: 'Overcooked', uz: "ko'p pishirilgan" },
      { id: '10-21', en: 'Underdone', uz: 'xom' },
      { id: '10-22', en: 'Grab a bite', uz: 'tezda tamaddi qilib olmoq' },
      { id: '10-23', en: 'Sweet tooth', uz: "shirinxo'r" },
      { id: '10-24', en: 'Tuck in', uz: 'ishtaha bilan yeyishni boshlamoq' },
      { id: '10-25', en: 'Comfort food', uz: "kayfiyatni ko'taruvchi taom" },
      { id: '10-26', en: 'Processed food', uz: 'qayta ishlangan ovqat' },
      { id: '10-27', en: 'Cuisine', uz: 'milliy oshxona, pishirish uslubi' },
      { id: '10-28', en: 'Ready meal', uz: 'tayyor ovqat' },
      { id: '10-29', en: 'Restrain hunger', uz: 'nafsini tiymoq' },
      { id: '10-30', en: 'Takeaway', uz: 'olib ketish uchun' },
      { id: '10-31', en: 'Dying of hunger', uz: "ochlikdan o'lay deyish, juda och qolish" },
      { id: '10-32', en: 'Full-up', uz: "to'yib ketmoq" },
      { id: '10-33', en: 'Bolt down', uz: 'shoshib yemoq, yamlamay yutish' },
      { id: '10-34', en: 'Eat like a horse', uz: "ko'p ovqat yemoq" },
      { id: '10-35', en: 'Spoil appetite', uz: 'ishtahani buzmoq' }
    ]
  },
  {
    id: 'unit-11',
    title: 'Unit 11: Holidays & Tourism',
    icon: '✈️',
    words: [
      { id: '11-1', en: 'Package holiday', uz: "tayyor sayohat paketi (hamma xarajatlar ichida)" },
      { id: '11-2', en: 'Breathtaking view', uz: 'maftunkor manzara' },
      { id: '11-3', en: 'Get away from it all', uz: "hamma narsadan dam olish, uzoqroqqa ketish" },
      { id: '11-4', en: 'Guided tour', uz: 'gid boshqaradigan sayohat' },
      { id: '11-5', en: 'Holiday destination', uz: 'tatil manzili' },
      { id: '11-6', en: 'Holiday of a lifetime', uz: 'umrga tatiydigan sayohat' },
      { id: '11-7', en: 'Holiday resort', uz: 'dam olish joyi' },
      { id: '11-8', en: 'Hordes of tourists', uz: "sayyohlarning katta oqimi, to'dasi" },
      { id: '11-9', en: 'Local crafts', uz: 'mahalliy hunarmandchilik' },
      { id: '11-10', en: 'Out of season', uz: 'mavsumdan tashqari' },
      { id: '11-11', en: 'Places of interest', uz: "qiziq bo'lgan joylar" },
      { id: '11-12', en: 'Sightseeing', uz: 'joylarni tomosha qilish' },
      { id: '11-13', en: 'Tourist trap', uz: 'sayyohlar uchun qimmat va gavjum joy' },
      { id: '11-14', en: 'Affordable destinations', uz: "cho'ntakbop manzillar" },
      { id: '11-15', en: 'Affordable travel', uz: "cho'ntakbop sayohat" },
      { id: '11-16', en: 'Landscapes', uz: 'manzaralar' },
      { id: '11-17', en: 'Scenic views', uz: "go'zal manzaralar" },
      { id: '11-18', en: 'Self-catering accommodation', uz: "o’zingiz ovqat tayyorlaydigan turar joy" },
      { id: '11-19', en: 'Architecture', uz: 'arxitektura' },
      { id: '11-20', en: 'Travel light', uz: 'kam yuk bilan' },
      { id: '11-21', en: 'Off the beaten track', uz: "kam o'rganilgan, chekka joyda" },
      { id: '11-22', en: 'Long-haul flight', uz: 'uzoq parvoz' },
      { id: '11-23', en: 'Swarmed with tourists', uz: "turistlar bilan to’lib toshgan" },
      { id: '11-24', en: 'Exotic destination', uz: 'ekzotik, noodatiy manzil' },
      { id: '11-25', en: 'Spectacular', uz: "ko'z yayraydigan" },
      { id: '11-26', en: 'Lush forest', uz: "qalin, yam-yashil o'rmon" },
      { id: '11-27', en: 'Value for money', uz: 'narxiga arziydigan' },
      { id: '11-28', en: 'Broaden horizons', uz: 'dunyoqarashni kengaytirmoq' },
      { id: '11-29', en: 'Wander streets', uz: "ko'chalarni kezmoq" },
      { id: '11-30', en: 'Customer service', uz: "mijozga xizmat ko'rsatish" },
      { id: '11-31', en: 'Souvenir', uz: "esdalik sovg'asi" },
      { id: '11-32', en: 'Itinerary', uz: "sayohat rejasi" },
      { id: '11-33', en: 'Boarding pass', uz: "qo'nish taloni" },
      { id: '11-34', en: 'Customs', uz: "bojxona" },
      { id: '11-35', en: 'Jet lag', uz: "vaqt almashishi natijasidagi charchoq" },
      { id: '11-36', en: 'Travel insurance', uz: "sayohat sug'urtasi" },
      { id: '11-37', en: 'Backpacking', uz: "ryukzak bilan sayohat qilish" },
      { id: '11-38', en: 'Tourist attraction', uz: "diqqatga sazovor joy" },
      { id: '11-39', en: 'Travel agency', uz: "sayohat agentligi" },
      { id: '11-40', en: 'Tour guide', uz: "gid, sayyohlik yo'lboshchisi" },
      { id: '11-41', en: 'All-inclusive', uz: "hamma xarajatlar ichida" },
      { id: '11-42', en: 'Check-in', uz: "ro'yxatdan o'tish" },
      { id: '11-43', en: 'Check-out', uz: "mehmonxonadan chiqish" },
      { id: '11-44', en: 'Departure', uz: "jo'nab ketish" },
      { id: '11-45', en: 'Arrival', uz: "yetib kelish" },
      { id: '11-46', en: 'Currency exchange', uz: "valyuta ayirboshlash" },
      { id: '11-47', en: 'Passport', uz: "pasport" },
      { id: '11-48', en: 'Visa', uz: "viza" }
    ]
  },
  {
    id: 'unit-12',
    title: 'Unit 12: Social Problems',
    icon: '🌍',
    words: [
      { id: '12-1', en: 'Daunting problem', uz: "qo'rqinchli, xavotirga soladigan muammo" },
      { id: '12-2', en: 'Complex issue', uz: 'murakkab masala, muammo' },
      { id: '12-3', en: 'Ongoing problem', uz: 'davom etayotgan muammo' },
      { id: '12-4', en: 'Unresolved problem', uz: 'yechilmagan muammo' },
      { id: '12-5', en: 'Pervasive problem', uz: 'keng tarqalgan muammo' },
      { id: '12-6', en: 'A burden on society', uz: "jamiyat uchun og'ir yuk" },
      { id: '12-7', en: 'A heated debate', uz: "qizg'in munozara" },
      { id: '12-8', en: 'Third world countries', uz: 'rivojlanmagan davlatlar' },
      { id: '12-9', en: 'Gap between rich and poor', uz: "boy va kambag'allar farqi" },
      { id: '12-10', en: 'Social inequality', uz: 'ijtimoiy tengsizlik' },
      { id: '12-11', en: 'Racial discrimination', uz: 'irqiy ayirmachilik' },
      { id: '12-12', en: 'Racism', uz: 'irqchilik' },
      { id: '12-13', en: 'Domestic violence', uz: "oilaviy zo'ravonlik" },
      { id: '12-14', en: 'Juvenile delinquency', uz: 'voyaga yetmaganlar jinoyatchiligi' },
      { id: '12-15', en: 'Political unrest', uz: 'siyosiy notinchlik, tartibsizliklar' },
      { id: '12-16', en: 'Brain drain', uz: "aqllar oqimi, mutaxassislarning chetga ko'chib ketishi" },
      { id: '12-17', en: 'Rising cost of living', uz: 'yashash xarajati oshishi' },
      { id: '12-18', en: 'Impoverished neighbourhood', uz: 'qashshoq mahalla, nochor hudud' },
      { id: '12-19', en: 'Run-down area', uz: 'xarobaga aylangan hudud' },
      { id: '12-20', en: 'Breakdown of families', uz: 'oilalar buzilishi' },
      { id: '12-21', en: 'Despair', uz: 'umidsizlik' },
      { id: '12-22', en: 'Address the problem', uz: "muammoga e'tibor qaratmoq, hal qilishga kirishmoq" },
      { id: '12-23', en: 'Tackle the problem', uz: 'muammoni hal qilish, kurashish' },
      { id: '12-24', en: 'Take action', uz: "chora ko'rmoq" },
      { id: '12-25', en: 'Leave things as they are', uz: "o'z holiga tashlab qo'ymoq" },
      { id: '12-26', en: 'Social welfare', uz: 'ijtimoiy farovonlik' },
      { id: '12-27', en: 'Social security', uz: 'ijtimoiy xavfsizlik' },
      { id: '12-28', en: 'Long-term measures', uz: 'uzoq muddatli choralar' },
      { id: '12-29', en: 'New/novel solutions', uz: 'yangi yechimlar' },
      { id: '12-30', en: 'The elite', uz: 'elita qatlam' },
      { id: '12-31', en: 'Distrust to the government', uz: "hukumatga bo'lgan ishonchsizlik" },
      { id: '12-32', en: 'Hatred', uz: 'nafrat' },
      { id: '12-33', en: 'Civilians', uz: 'tinch aholi' },
      { id: '12-34', en: 'Transparency', uz: 'shaffoflik, ochiqlik' },
      { id: '12-35', en: 'Low-income household', uz: 'kam daromadli oila' },
      { id: '12-36', en: 'Cut expenses', uz: 'xarajatlarni kamaytirmoq' },
      { id: '12-37', en: 'Overpopulation', uz: 'aholi zichligi, aholining haddan tashqari ko\'payishi' },
      { id: '12-38', en: 'Death-sentence', uz: "o'lim jazosi" },
      { id: '12-39', en: 'Detrimental', uz: 'zararli' },
      { id: '12-40', en: 'Intervention', uz: 'aralashuv, davlat aralashuvi' }
    ]
  }
];
